# -*- coding: utf-8 -*-
"""Que visual acompana a cada concepto de Bases de Datos II: animacion, foto o nada.

Clave: el comienzo del titulo de la seccion `###` del fundamento (sin tildes ni mayusculas
importan: se compara normalizado). Valor:

- ``anim``: carpeta/huella en `config/animaciones/` (renderizada a GIF por `renderizar.py`).
  En la lamina, sus pasos aparecen uno por clic del docente.
- ``foto``: consulta para Pexels, en ingles. Se usa en las laminas que no tienen animacion.

Una seccion sin entrada se queda en texto a ancho completo: el visual se pone donde explica,
no por decorar. Las laminas de codigo nunca llevan visual (el codigo necesita el ancho).
"""

VISUALES = {
    4: {
        "Funcion y procedimiento": {"anim": "bd2/clase4/funcion-o-procedimiento"},
        "Los tres detalles de fn_precio_consulta": {"anim": "bd2/clase4/fn-precio-consulta"},
        "El trigger: el unico que nadie invoca": {"anim": "bd2/clase4/trigger-dos-objetos"},
        "BEFORE o AFTER": {"anim": "bd2/clase4/before-after"},
        "La auditoria": {"anim": "bd2/clase4/auditoria-when"},
        "El trigger que impide": {"anim": "bd2/clase4/trigger-que-impide"},
        "Las cuatro capas": {"anim": "bd2/clase4/cuatro-capas"},
        "Cuando NO se usa un trigger": {"anim": "bd2/clase4/cuando-no-trigger"},
        "Seguridad y respaldo": {"anim": "bd2/clase4/seguridad-respaldo"},
        "RPO y RTO": {"anim": "bd2/clase4/rpo-rto"},
    },
    8: {
        "Que es una transaccion, y las dos": {"anim": "bd2/clase8/transaccion-unidad"},
        "Atomicidad: el fallo concreto": {"anim": "bd2/clase8/atomicidad-corte"},
        "Consistencia: valido es lo que": {"anim": "bd2/clase8/consistencia-restriccion"},
        "Aislamiento: el fallo mas facil": {"anim": "bd2/clase8/actualizacion-perdida"},
        "Durabilidad: el registro de transacciones": {"anim": "bd2/clase8/wal-commit"},
        "La firma de sp_facturar": {"anim": "bd2/clase8/sp-facturar-arreglos"},
        "El guardia del stock": {"anim": "bd2/clase8/guardia-stock"},
        "Error del motor y error de negocio": {"anim": "bd2/clase8/error-motor-negocio"},
        "Donde empieza y termina la transaccion": {"anim": "bd2/clase8/call-transaccion"},
        "El savepoint implicito del bloque": {"anim": "bd2/clase8/savepoint-exception"},
        "Abortar o informar": {"anim": "bd2/clase8/abortar-o-informar"},
        "Tuning: habitos de escritura": {"anim": "bd2/clase8/transaccion-corta"},
    },
    10: {
        "La transaccion como unidad de todo": {"anim": "bd2/clase10/intercalado-doble-cita"},
        "Serializar de verdad existe": {"anim": "bd2/clase10/serializar-cuesta"},
        "Los tres fenomenos indeseables": {"anim": "bd2/clase10/tres-fenomenos"},
        "Los cuatro niveles de aislamiento": {"anim": "bd2/clase10/niveles-aislamiento"},
        "Control pesimista: SELECT": {"anim": "bd2/clase10/for-update"},
        "Control optimista: verificar": {"anim": "bd2/clase10/version-optimista"},
        "Deadlock: la escena de VetCare": {"anim": "bd2/clase10/deadlock-ciclo"},
        "Antes de los niveles: la restriccion": {"anim": "bd2/clase10/unique-una-linea"},
    },
    1: {
        "Por que esto no es Bases de Datos I": {"anim": "bd2/clase1/tabla-fila-columna"},
        "Nivel conceptual y nivel fisico": {"anim": "bd2/clase1/conceptual-fisico"},
        "Clave primaria: natural o sustituta": {"anim": "bd2/clase1/pk-natural-sustituta"},
        "Normalizacion 1FN-3FN: primero la enfermedad": {"anim": "bd2/clase1/anomalias"},
        "Clave foranea, borrado y por que": {"anim": "bd2/clase1/fk-restrictiva"},
        "Baja logica: activa CHAR(1)": {"anim": "bd2/clase1/baja-logica"},
        "Que separa un diagrama ER": {"anim": "bd2/clase1/er-vs-dibujo"},
        "Tipos de datos: donde se pagan": {"anim": "bd2/clase1/tipos-de-datos"},
        "Convenciones de nombres para que": {"anim": "bd2/clase1/nombres-minusculas"},
        "Del ER dibujado al codigo Mermaid": {"anim": "bd2/clase1/er-a-mermaid"},
    },
    2: {
        "Los cuatro terminos que se confunden": {"anim": "bd2/clase2/cuatro-terminos"},
        "Privilegio: la unidad atomica": {"anim": "bd2/clase2/privilegio-ddl-dml"},
        "Rol: por que existe": {"anim": "bd2/clase2/rol-aritmetica"},
        "En PostgreSQL usuario y rol": {"anim": "bd2/clase2/login-nologin"},
        "Minimo privilegio aplicado a VetCare": {"anim": "bd2/clase2/minimo-privilegio"},
        "Separacion de funciones: el ejemplo": {"anim": "bd2/clase2/separacion-funciones"},
        "GRANT y REVOKE: la sintaxis": {"anim": "bd2/clase2/grant-revoke"},
        "WITH GRANT OPTION y PUBLIC": {"anim": "bd2/clase2/grant-option-public"},
        "Cuando el GRANT es demasiado": {"anim": "bd2/clase2/vista-columna"},
        "La matriz como hecho verificable": {"anim": "bd2/clase2/information-schema"},
        "La politica de altas y bajas": {"anim": "bd2/clase2/altas-bajas"},
        "El motor de hoy es PostgreSQL": {"anim": "bd2/clase2/set-role-prueba"},
        "La matriz es la decision": {"anim": "bd2/clase2/matriz-decision"},
    },
    11: {
        "Que es una revision tecnica": {"anim": "bd2/clase11/revision-roles"},
        "Lo que se audita es la coherencia": {"anim": "bd2/clase11/coherencia-piezas"},
        "Verificaciones uno y dos": {"anim": "bd2/clase11/er-contra-ddl"},
        "Verificacion tres: que compile": {"anim": "bd2/clase11/compila-funciona"},
        "Scope creep": {"anim": "bd2/clase11/scope-creep"},
        "La anatomia fija de la retroalimentacion": {"anim": "bd2/clase11/anatomia-hallazgo"},
        "Un checkpoint sin hallazgos": {"anim": "bd2/clase11/checkpoint"},
    },
    12: {
        "Integrar no es conectarse": {"anim": "bd2/clase12/puerta-unica"},
        "Inyeccion SQL": {"anim": "bd2/clase12/inyeccion-sql"},
        "Por que el parametro lo evita": {"anim": "bd2/clase12/parametro"},
        "El contrato y sus seis partes": {"anim": "bd2/clase12/contrato-seis"},
        "El manejo de errores entre capas": {"anim": "bd2/clase12/errores-capas"},
        "El pool de conexiones": {"anim": "bd2/clase12/pool-conexiones"},
        "Logica en la base o en la aplicacion": {"anim": "bd2/clase12/logica-base-app"},
        "Cambiar el esquema sin romper": {"anim": "bd2/clase12/expandir-contraer"},
    },
    13: {
        "El post-mortem analiza el fallo": {"anim": "bd2/clase13/post-mortem"},
        "Causa proxima y causa raiz": {"anim": "bd2/clase13/causa-raiz"},
        "Caso uno: el respaldo": {"anim": "bd2/clase13/gitlab-2017"},
        "Caso dos: permisos excesivos": {"anim": "bd2/clase13/capital-one"},
        "Caso tres: perdida de datos": {"anim": "bd2/clase13/migracion-sin-retorno"},
        "Caso cuatro: concurrencia": {"anim": "bd2/clase13/actualizacion-perdida"},
        "Lecciones accionables": {"anim": "bd2/clase13/leccion-accionable"},
    },
    15: {
        "Sustentar no es describir": {"anim": "bd2/clase15/describir-sustentar"},
        "Las cuatro preguntas de por que": {"anim": "bd2/clase15/cuatro-porques"},
        "La cuarta pregunta, la que mas": {"anim": "bd2/clase15/trigger-cobertura"},
        "Reproducible: un tercero": {"anim": "bd2/clase15/carpeta-reproducible"},
        "El reparto de los 5 a 8": {"anim": "bd2/clase15/reparto-minutos"},
        "El Q&A de modelado": {"anim": "bd2/clase15/dos-pelusa"},
    },
    3: {
        "Que es un procedimiento almacenado": {"anim": "bd2/clase3/que-es-procedimiento"},
        "El molde de PL/pgSQL": {"anim": "bd2/clase3/molde-plpgsql"},
        "Los modos de parametro": {"anim": "bd2/clase3/modos-parametro"},
        "RAISE EXCEPTION: la validacion": {"anim": "bd2/clase3/raise-aborta"},
        "Donde debe vivir la logica": {"anim": "bd2/clase3/donde-logica"},
        "La inyeccion de SQL": {"anim": "bd2/clase3/inyeccion-sql"},
        "La bateria de pruebas": {"anim": "bd2/clase3/bateria-do"},
        "Que significa la columna paso": {"anim": "bd2/clase3/trampa-when-others"},
        "El contrato del procedimiento": {"anim": "bd2/clase3/contrato-seis-bloques"},
        "Procedimiento y funcion": {"anim": "bd2/clase3/procedimiento-funcion"},
        "Depurar sin depurador": {"anim": "bd2/clase3/depurar-cuatro"},
        "El motor de hoy es PostgreSQL": {"anim": "bd2/clase3/oracle-postgres"},
        "El segundo procedimiento": {"anim": "bd2/clase3/exists-consulta"},
        "Como amarra con las clases vecinas": {"anim": "bd2/clase3/amarre-clases"},
    },
    6: {
        "SQL es declarativo: quien decide": {"anim": "bd2/clase6/sql-declarativo"},
        "Leer un plan: es un arbol": {"anim": "bd2/clase6/leer-plan"},
        "Las estadisticas: metadatos que describen": {"anim": "bd2/clase6/estadisticas"},
        "Cardinalidad y selectividad: por que": {"anim": "bd2/clase6/selectividad"},
        "Full table scan contra index scan": {"anim": "bd2/clase6/seq-vs-index"},
        "Predicado sargable: el antipatron": {"anim": "bd2/clase6/sargable"},
        "La subconsulta correlacionada: 2.006 pasadas": {"anim": "bd2/clase6/subconsulta-correlacionada"},
        "Optimizar no cambia el resultado": {"anim": "bd2/clase6/mismo-resultado"},
    },
    7: {
        "De donde viene la clase": {"anim": "bd2/clase7/indice-puntero"},
        "El B-Tree por dentro": {"anim": "bd2/clase7/btree"},
        "El precio se paga en cada escritura": {"anim": "bd2/clase7/precio-escritura"},
        "Indice compuesto: la regla del prefijo": {"anim": "bd2/clase7/prefijo-izquierdo"},
        "Cuando el indice responde solo": {"anim": "bd2/clase7/index-only"},
        "La secuencia de medicion, y por que": {"anim": "bd2/clase7/secuencia-medicion"},
        "El experimento del orden de columnas": {"anim": "bd2/clase7/orden-columnas"},
        "El indice parcial: que indexa": {"anim": "bd2/clase7/indice-parcial"},
        "Particionar: que es, y por que": {"anim": "bd2/clase7/particionar"},
        "El DDL de la particion": {"anim": "bd2/clase7/ddl-particion"},
    },
}
