# -*- coding: utf-8 -*-
"""Consultas proyectadas de Bases de Datos II: el SQL que se dicta, por clase.

Por que existe
--------------
Bases de Datos II es la materia de las consultas y su deck proyectaba 42 laminas de codigo
sobre 532: el 7%. Todo el SQL que existia en el material ya esta extraido —`CODIGO_SLIDE` y
las sentencias que estaban escritas dentro de la prosa—, asi que subir de ahi era escribir
consultas nuevas. Esto es eso.

La regla que gobierna lo que se escribe aqui
--------------------------------------------
CLAUDE.md §0: **nada se evalua que no se haya ensenado, y nada se ensena que no se use.** Cada
clase de aqui ensena el MECANISMO que su actividad de ExamLab evalua, y lo ensena sobre un
ejemplo ADYACENTE, no sobre el enunciado.

El caso mas claro es la Clase 1: su actividad pide al estudiante escribir el DDL de `dueno`,
`mascota` y `cita`. Proyectar ese DDL seria publicar la respuesta. Asi que el patron —clave
primaria sustituta, FK, CHECK, DEFAULT— se ensena sobre `veterinario` e `insumo`, que son
tablas del mismo modelo VetCare y no son lo que la actividad pide. El estudiante ve el
mecanismo completo y sigue teniendo que decidir el suyo.

Convenciones que respeta todo el SQL de este archivo (son las del curso, y son lo que hace
que el script del estudiante corra a la primera):
  - PostgreSQL, no Oracle: `SERIAL`/`GENERATED ALWAYS AS IDENTITY`, `TEXT`/`VARCHAR`,
    `TIMESTAMP`, `NOW()`. No existen `NUMBER` ni `VARCHAR2` ni `SYSDATE`.
  - todo en minusculas y sin comillas dobles;
  - tablas en singular y sin tildes: `dueno`, `mascota`, `cita`, `veterinario`, `consulta`,
    `insumo`, `factura`, `detalle_factura`;
  - identificadores sustitutos `id_<entidad>`, con el mismo nombre en las dos tablas.

Limite declarado (CLAUDE.md): **este SQL no se ejecuto.** No hay PostgreSQL en el entorno de
generacion. Esta verificado por lectura contra el esquema y las convenciones del curso; la
comprobacion de ejecucion es en ExamLab, que corre PGlite en el navegador.
"""

#: `{clase: [(titulo, [lineas]), ...]}`. Cada entrada es una lamina de codigo.
QUERIES = {

    # ── Clase 1 · DDL, integridad y el primer JOIN ───────────────────────────
    # Evalua: DDL con PK/FK/CHECK/DEFAULT, insertar datos, JOIN de tres tablas y
    # reconocer que el DDL solo no defiende una regla de negocio.
    # Se ensena sobre `veterinario` e `insumo`: la actividad pide dueno/mascota/cita.
    1: [
        ("El patron de tabla: PK, obligatorios y dominio cerrado", [
            "-- Mismo patron que pedira su DDL, sobre otra tabla del modelo.",
            "CREATE TABLE veterinario (",
            "  id_veterinario SERIAL PRIMARY KEY,      -- sustituta: la genera la base",
            "  tarjeta_prof   VARCHAR(30) UNIQUE,      -- natural: unica, pero puede faltar",
            "  nombre         VARCHAR(80) NOT NULL,    -- obligatorio",
            "  especialidad   VARCHAR(40) NOT NULL",
            "    CHECK (especialidad IN ('GENERAL','CIRUGIA','DERMATOLOGIA')),",
            "  activo         CHAR(1) DEFAULT 'S'      -- baja logica, no DELETE",
            "    CHECK (activo IN ('S','N'))",
            ");",
        ]),
        ("La clave foranea y que pasa al borrar el padre", [
            "CREATE TABLE insumo (",
            "  id_insumo  SERIAL PRIMARY KEY,",
            "  nombre     VARCHAR(80) NOT NULL,",
            "  stock      INT NOT NULL DEFAULT 0 CHECK (stock >= 0),",
            "  precio     DECIMAL(12,2) NOT NULL CHECK (precio > 0)",
            ");",
            "",
            "-- El comportamiento al borrar el padre SE ELIGE. Si no se declara,",
            "-- PostgreSQL asume NO ACTION: se niega a borrar. Eso es del estandar.",
            "ALTER TABLE detalle_factura",
            "  ADD CONSTRAINT fk_detalle_insumo",
            "  FOREIGN KEY (id_insumo) REFERENCES insumo (id_insumo)",
            "  ON DELETE RESTRICT;   -- no se borra un insumo ya facturado",
        ]),
        ("Integridad referencial: el error que devuelve el motor", [
            "-- Existe la mascota 1, no existe la 999.",
            "INSERT INTO cita (id_mascota, fecha_hora, estado)",
            "VALUES (1, TIMESTAMP '2026-09-01 09:00:00', 'PROGRAMADA');",
            "-- INSERT 0 1",
            "",
            "INSERT INTO cita (id_mascota, fecha_hora, estado)",
            "VALUES (999, TIMESTAMP '2026-09-01 10:00:00', 'PROGRAMADA');",
            "-- ERROR:  insert or update on table \"cita\" violates foreign key",
            "--         constraint \"cita_id_mascota_fkey\"",
            "-- DETAIL:  Key (id_mascota)=(999) is not present in table \"mascota\".",
        ]),
        ("El JOIN de tres tablas", [
            "SELECT m.nombre    AS mascota,",
            "       d.nombre    AS dueno,",
            "       c.fecha_hora,",
            "       c.estado",
            "FROM cita c",
            "JOIN mascota m ON m.id_mascota = c.id_mascota",
            "JOIN dueno   d ON d.id_dueno   = m.id_dueno",
            "WHERE c.fecha_hora >= DATE '2026-09-01'",
            "  AND m.activa = 'S'",
            "ORDER BY c.fecha_hora;",
        ]),
        ("Lo que el DDL NO puede defender solo", [
            "-- La FK garantiza que el identificador EXISTA. No que el negocio lo quiera.",
            "UPDATE mascota SET activa = 'N' WHERE id_mascota = 1;   -- baja logica",
            "",
            "INSERT INTO cita (id_mascota, fecha_hora, estado)",
            "VALUES (1, TIMESTAMP '2026-09-02 08:00:00', 'PROGRAMADA');",
            "-- INSERT 0 1   <-- la acepta: para el motor la mascota 1 existe",
            "",
            "-- Un CHECK tampoco: solo mira columnas de SU propia fila.",
            "-- La regla «una mascota inactiva no agenda» necesita consultar OTRA tabla,",
            "-- y eso es un procedimiento (Clase 3) o un trigger (Clase 4).",
        ]),
    ],

    # ── Clase 2 · Roles, privilegios y minimo privilegio ─────────────────────
    2: [
        ("Crear el rol y otorgar solo lo que el cargo usa", [
            "-- En PostgreSQL usuario y rol son lo mismo: LOGIN es lo que los distingue.",
            "CREATE ROLE recepcion LOGIN PASSWORD 'cambiar_en_produccion';",
            "CREATE ROLE veterinario_rol NOLOGIN;   -- rol de permisos, no de acceso",
            "",
            "-- La recepcionista agenda: no lee historias clinicas ni toca facturas.",
            "GRANT SELECT, INSERT, UPDATE ON cita    TO recepcion;",
            "GRANT SELECT                 ON mascota TO recepcion;",
            "GRANT SELECT                 ON dueno   TO recepcion;",
            "GRANT USAGE, SELECT ON SEQUENCE cita_id_cita_seq TO recepcion;",
            "-- Sin USAGE en la secuencia, el INSERT falla: el SERIAL la necesita.",
        ]),
        ("REVOKE, y los dos que hacen dano en silencio", [
            "REVOKE UPDATE ON cita FROM recepcion;   -- quitar es tan explicito como dar",
            "",
            "-- PUBLIC es todo el mundo, presente y futuro. Casi nunca es lo que se quiere.",
            "REVOKE ALL ON consulta FROM PUBLIC;",
            "",
            "-- WITH GRANT OPTION deja que el que recibe vuelva a otorgar.",
            "GRANT SELECT ON cita TO auditor WITH GRANT OPTION;",
            "-- auditor puede ahora hacer: GRANT SELECT ON cita TO cualquiera;",
            "-- Para deshacerlo hay que arrastrar lo que el concedio:",
            "REVOKE SELECT ON cita FROM auditor CASCADE;",
        ]),
        ("Cuando el GRANT sobra: vista y privilegio por columna", [
            "-- La recepcion necesita la agenda, no el motivo clinico de la consulta.",
            "CREATE VIEW v_agenda_dia AS",
            "SELECT c.id_cita, c.fecha_hora, c.estado,",
            "       m.nombre AS mascota, d.telefono",
            "FROM cita c",
            "JOIN mascota m ON m.id_mascota = c.id_mascota",
            "JOIN dueno   d ON d.id_dueno   = m.id_dueno;",
            "",
            "GRANT SELECT ON v_agenda_dia TO recepcion;",
            "",
            "-- O el privilegio acotado a columnas, sin crear objeto nuevo:",
            "GRANT SELECT (id_mascota, nombre, especie) ON mascota TO recepcion;",
            "GRANT UPDATE (telefono, email)             ON dueno   TO recepcion;",
        ]),
        ("La matriz como hecho verificable, no como documento", [
            "-- Lo que el motor dice que concedio, que no siempre es lo que se creia.",
            "SELECT grantee, table_name, privilege_type",
            "FROM information_schema.role_table_grants",
            "WHERE grantee IN ('recepcion','veterinario_rol','auditor')",
            "ORDER BY grantee, table_name, privilege_type;",
            "",
            "-- Y los privilegios por columna, que la consulta anterior no muestra:",
            "SELECT grantee, table_name, column_name, privilege_type",
            "FROM information_schema.column_privileges",
            "WHERE grantee = 'recepcion'",
            "ORDER BY table_name, column_name;",
        ]),
    ],

    # ── Clase 3 · Procedimientos almacenados ────────────────────────────────
    3: [
        ("El molde de un procedimiento en PL/pgSQL", [
            "CREATE OR REPLACE PROCEDURE sp_dar_de_baja_insumo(",
            "  p_id_insumo INT,",
            "  p_motivo    VARCHAR",
            ")",
            "LANGUAGE plpgsql",
            "AS $$",
            "DECLARE",
            "  v_stock INT;",
            "BEGIN",
            "  SELECT stock INTO v_stock FROM insumo WHERE id_insumo = p_id_insumo;",
            "",
            "  IF v_stock IS NULL THEN",
            "    RAISE EXCEPTION 'El insumo % no existe', p_id_insumo;",
            "  END IF;",
            "",
            "  UPDATE insumo SET stock = 0 WHERE id_insumo = p_id_insumo;",
            "END;",
            "$$;",
        ]),
        ("RAISE EXCEPTION: la validacion que aborta y deshace", [
            "-- La regla que la FK no puede defender: validar contra OTRA tabla.",
            "IF NOT EXISTS (SELECT 1 FROM mascota",
            "               WHERE id_mascota = p_id_mascota AND activa = 'S') THEN",
            "  RAISE EXCEPTION 'La mascota % no existe o esta inactiva', p_id_mascota;",
            "END IF;",
            "",
            "-- Lo que hay que subrayar: RAISE EXCEPTION no solo avisa, DESHACE.",
            "-- Todo lo que el procedimiento haya escrito antes se revierte.",
            "-- Por eso el orden natural es: validar primero, escribir despues.",
        ]),
        ("La bateria de pruebas: un bloque DO por caso", [
            "-- Caso OK",
            "CALL sp_dar_de_baja_insumo(1, 'vencido');",
            "",
            "-- Caso de error, capturado para que el guion no se detenga",
            "DO $$",
            "BEGIN",
            "  CALL sp_dar_de_baja_insumo(9999, 'inexistente');",
            "  RAISE NOTICE 'FALLO LA PRUEBA: debio rechazar el insumo 9999';",
            "EXCEPTION WHEN OTHERS THEN",
            "  RAISE NOTICE 'OK - rechazado como se esperaba: %', SQLERRM;",
            "END;",
            "$$;",
        ]),
        ("PROCEDURE o FUNCTION: la diferencia es donde se puede usar", [
            "-- FUNCTION devuelve un valor y se puede usar DENTRO de un SELECT.",
            "CREATE OR REPLACE FUNCTION fn_citas_del_dia(p_dia DATE)",
            "RETURNS INT",
            "LANGUAGE sql",
            "AS $$",
            "  SELECT COUNT(*)::INT FROM cita",
            "  WHERE fecha_hora >= p_dia AND fecha_hora < p_dia + 1;",
            "$$;",
            "",
            "SELECT fn_citas_del_dia(DATE '2026-09-01');   -- se puede",
            "",
            "-- PROCEDURE no: se invoca con CALL y puede manejar transacciones.",
            "-- SELECT sp_dar_de_baja_insumo(1,'x');  -- ERROR: no es una funcion",
        ]),
    ],

    # ── Clase 4 · Funciones y triggers ──────────────────────────────────────
    4: [
        ("La funcion de tarifas, y por que IMMUTABLE importa", [
            "CREATE OR REPLACE FUNCTION fn_recargo_festivo(p_base DECIMAL, p_dia DATE)",
            "RETURNS DECIMAL",
            "LANGUAGE plpgsql",
            "IMMUTABLE               -- mismo resultado para los mismos argumentos",
            "AS $$",
            "BEGIN",
            "  IF EXTRACT(DOW FROM p_dia) IN (0, 6) THEN   -- 0 domingo, 6 sabado",
            "    RETURN ROUND(p_base * 1.25, 2);",
            "  END IF;",
            "  RETURN ROUND(p_base, 2);",
            "END;",
            "$$;",
            "",
            "-- IMMUTABLE permite indexar la expresion y cachear el resultado. Una funcion",
            "-- que lee NOW() o una tabla NO es inmutable: seria STABLE o VOLATILE.",
        ]),
        ("Un trigger son DOS objetos: la funcion y la asociacion", [
            "-- 1. la funcion, que devuelve trigger y ve OLD y NEW",
            "CREATE OR REPLACE FUNCTION fn_trg_audit_cita()",
            "RETURNS trigger",
            "LANGUAGE plpgsql",
            "AS $$",
            "BEGIN",
            "  INSERT INTO auditoria_cita (id_cita, estado_ant, estado_nue, cambiado_en)",
            "  VALUES (OLD.id_cita, OLD.estado, NEW.estado, NOW());",
            "  RETURN NEW;          -- en AFTER el valor se ignora, pero no se omite",
            "END;",
            "$$;",
            "",
            "-- 2. la asociacion, que dice CUANDO se dispara",
            "CREATE TRIGGER trg_audit_cita",
            "AFTER UPDATE OF estado ON cita",
            "FOR EACH ROW",
            "WHEN (OLD.estado IS DISTINCT FROM NEW.estado)   -- no auditar no-cambios",
            "EXECUTE FUNCTION fn_trg_audit_cita();",
        ]),
        ("BEFORE o AFTER: uno puede impedir, el otro solo registrar", [
            "-- BEFORE puede cambiar NEW o abortar. Es el que IMPIDE.",
            "CREATE OR REPLACE FUNCTION fn_trg_stock_no_negativo()",
            "RETURNS trigger",
            "LANGUAGE plpgsql",
            "AS $$",
            "BEGIN",
            "  IF NEW.stock < 0 THEN",
            "    RAISE EXCEPTION 'Stock negativo en el insumo % (%)', NEW.id_insumo, NEW.stock;",
            "  END IF;",
            "  RETURN NEW;          -- en BEFORE, devolver NULL cancela la operacion",
            "END;",
            "$$;",
            "",
            "CREATE TRIGGER trg_stock_no_negativo",
            "BEFORE UPDATE OF stock ON insumo",
            "FOR EACH ROW EXECUTE FUNCTION fn_trg_stock_no_negativo();",
        ]),
        ("Las cuatro capas, y en cual vive cada regla", [
            "-- 1. CHECK: mira SOLO columnas de su propia fila. Barato y siempre activo.",
            "ALTER TABLE insumo ADD CONSTRAINT ck_precio_pos CHECK (precio > 0);",
            "",
            "-- 2. PROCEDIMIENTO: necesita consultar otra tabla. Solo aplica si se llama.",
            "--    IF NOT EXISTS (SELECT 1 FROM mascota WHERE ... AND activa='S') ...",
            "",
            "-- 3. TRIGGER: necesita otra tabla Y tiene que aplicar aunque nadie llame.",
            "--    Es la unica capa que no se puede saltar por la puerta de atras.",
            "",
            "-- 4. APLICACION: mensajes al usuario y reglas de pantalla. Nunca la ULTIMA",
            "--    linea de defensa: un psql abierto la deja en cero.",
        ]),
    ],

    # ── Clase 6 · Optimizacion de consultas ─────────────────────────────────
    6: [
        ("El antipatron y su reescritura", [
            "-- ANTES: funcion sobre la columna -> el indice de fecha_hora no se usa",
            "SELECT * FROM cita",
            "WHERE TO_CHAR(fecha_hora, 'YYYY-MM-DD') = '2026-09-01';",
            "",
            "-- DESPUES: rango sobre la columna desnuda -> el indice si se usa",
            "SELECT c.id_cita, c.fecha_hora, m.nombre",
            "FROM cita c",
            "JOIN mascota m ON m.id_mascota = c.id_mascota",
            "WHERE c.fecha_hora >= TIMESTAMP '2026-09-01 00:00:00'",
            "  AND c.fecha_hora <  TIMESTAMP '2026-09-02 00:00:00';",
            "",
            "-- La regla: nunca envolver en una funcion la columna por la que se filtra.",
        ]),
        ("EXPLAIN ANALYZE: la evidencia, no la opinion", [
            "EXPLAIN (ANALYZE, BUFFERS)",
            "SELECT c.id_cita, c.fecha_hora, m.nombre",
            "FROM cita c JOIN mascota m ON m.id_mascota = c.id_mascota",
            "WHERE c.fecha_hora >= TIMESTAMP '2026-09-01 00:00:00'",
            "  AND c.fecha_hora <  TIMESTAMP '2026-09-02 00:00:00';",
            "",
            "-- Lo que se lee, en este orden:",
            "--   Seq Scan  -> recorre la tabla entera",
            "--   Index Scan / Bitmap Heap Scan -> usa el indice",
            "--   actual time=...  el tiempo REAL (EXPLAIN solo estima; ANALYZE ejecuta)",
            "--   rows=...  comparar con las filas estimadas: si difieren mucho, ANALYZE",
        ]),
        ("Matar la subconsulta correlacionada", [
            "-- ANTES: la subconsulta se ejecuta UNA VEZ POR DUENO",
            "SELECT d.nombre,",
            "       (SELECT COUNT(*) FROM mascota m WHERE m.id_dueno = d.id_dueno) AS n",
            "FROM dueno d;",
            "",
            "-- DESPUES: una sola pasada, agrupando",
            "SELECT d.nombre, COUNT(m.id_mascota) AS n",
            "FROM dueno d",
            "LEFT JOIN mascota m ON m.id_dueno = d.id_dueno",
            "GROUP BY d.id_dueno, d.nombre",
            "ORDER BY n DESC;",
            "",
            "-- LEFT JOIN, no JOIN: con JOIN desaparecen los duenos sin mascota.",
        ]),
    ],

    # ── Clase 7 · Indices y particionamiento ────────────────────────────────
    7: [
        ("Crear el indice y probar que se usa", [
            "CREATE INDEX idx_cita_fecha_hora ON cita (fecha_hora);",
            "CREATE INDEX idx_mascota_dueno    ON mascota (id_dueno);",
            "ANALYZE cita;      -- sin estadisticas frescas el planificador decide a ciegas",
            "",
            "EXPLAIN ANALYZE",
            "SELECT * FROM cita",
            "WHERE fecha_hora >= TIMESTAMP '2026-09-01 00:00:00'",
            "  AND fecha_hora <  TIMESTAMP '2026-09-02 00:00:00';",
            "",
            "-- Antes:   Seq Scan on cita  (rows=30010)",
            "-- Despues: Index Scan using idx_cita_fecha_hora on cita  (rows=41)",
        ]),
        ("El orden de columnas en un indice compuesto", [
            "-- Consulta: filtra por id_veterinario y ordena por fecha_hora",
            "CREATE INDEX idx_cita_vet_fecha ON cita (id_veterinario, fecha_hora);",
            "",
            "-- Sirve para:",
            "--   WHERE id_veterinario = 3                      -> si (prefijo)",
            "--   WHERE id_veterinario = 3 ORDER BY fecha_hora  -> si (prefijo + orden)",
            "-- NO sirve para:",
            "--   WHERE fecha_hora >= ...                       -> no (no es prefijo)",
            "",
            "-- La regla: primero la columna de IGUALDAD, despues la de RANGO u ORDEN.",
        ]),
        ("Particionar el historico por rango de fecha", [
            "CREATE TABLE cita_hist (",
            "  id_cita     INT NOT NULL,",
            "  id_mascota  INT NOT NULL,",
            "  fecha_hora  TIMESTAMP NOT NULL,",
            "  estado      VARCHAR(20) NOT NULL",
            ") PARTITION BY RANGE (fecha_hora);",
            "",
            "CREATE TABLE cita_hist_2025 PARTITION OF cita_hist",
            "  FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');",
            "CREATE TABLE cita_hist_2026 PARTITION OF cita_hist",
            "  FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');",
            "",
            "-- La clave de particion TIENE que estar en la PK si hay PK: la unicidad",
            "-- se garantiza por particion, no entre particiones.",
        ]),
        ("El costo de sobre-indexar, que casi nunca se menciona", [
            "-- Cada indice se ACTUALIZA en cada INSERT, UPDATE y DELETE.",
            "-- Seis indices sobre cita = seis escrituras extra por cita agendada.",
            "",
            "-- Que indices existen y cuanto pesan:",
            "SELECT indexrelname, idx_scan, pg_size_pretty(pg_relation_size(indexrelid))",
            "FROM pg_stat_user_indexes",
            "WHERE relname = 'cita'",
            "ORDER BY idx_scan;",
            "",
            "-- idx_scan = 0 despues de dias de uso: el indice no sirve a nadie y",
            "-- se esta pagando en cada escritura. Candidato a DROP INDEX.",
        ]),
    ],

    # ── Clase 8 · Transacciones y tuning ────────────────────────────────────
    8: [
        ("Todo o nada: la transaccion explicita", [
            "BEGIN;",
            "",
            "INSERT INTO factura (id_dueno, fecha, total)",
            "VALUES (1, NOW(), 0) RETURNING id_factura;   -- devuelve el id generado",
            "",
            "INSERT INTO detalle_factura (id_factura, id_insumo, cantidad, precio_unitario)",
            "VALUES (100, 5, 2, 15000.00);",
            "",
            "UPDATE insumo SET stock = stock - 2 WHERE id_insumo = 5;",
            "",
            "COMMIT;      -- o ROLLBACK; y no queda rastro de ninguna de las tres",
        ]),
        ("SAVEPOINT: deshacer una parte sin perder el resto", [
            "BEGIN;",
            "INSERT INTO factura (id_dueno, fecha, total) VALUES (1, NOW(), 0);",
            "",
            "SAVEPOINT antes_del_detalle;",
            "INSERT INTO detalle_factura (id_factura, id_insumo, cantidad, precio_unitario)",
            "VALUES (100, 9999, 1, 1000.00);      -- insumo inexistente: falla",
            "",
            "ROLLBACK TO SAVEPOINT antes_del_detalle;   -- la factura sigue viva",
            "",
            "INSERT INTO detalle_factura (id_factura, id_insumo, cantidad, precio_unitario)",
            "VALUES (100, 5, 1, 1000.00);",
            "COMMIT;",
        ]),
        ("El bloque EXCEPTION y la trampa que cuesta puntos", [
            "BEGIN",
            "  UPDATE insumo SET stock = stock - p_cantidad WHERE id_insumo = p_id;",
            "  INSERT INTO detalle_factura (...) VALUES (...);",
            "EXCEPTION WHEN OTHERS THEN",
            "  RAISE NOTICE 'algo fallo: %', SQLERRM;   -- <-- LA TRAMPA",
            "END;",
            "",
            "-- Capturar la excepcion y solo avisar CONFIRMA lo demas: el UPDATE del stock",
            "-- queda aplicado y el detalle no. La factura miente.",
            "-- Si se captura, hay que RE-LANZAR para que el bloque entero se deshaga:",
            "EXCEPTION WHEN OTHERS THEN",
            "  RAISE;      -- vuelve a lanzar la misma excepcion",
        ]),
    ],

    # ── Clase 10 · Concurrencia (autonoma) ──────────────────────────────────
    10: [
        ("La doble reserva, y la restriccion que la cierra de raiz", [
            "-- Dos sesiones agendan la misma franja al mismo veterinario:",
            "-- T1: SELECT COUNT(*) FROM cita WHERE id_veterinario=3 AND fecha_hora=X; -> 0",
            "-- T2: SELECT COUNT(*) ... mismo resultado -> 0",
            "-- T1: INSERT ... ok      T2: INSERT ... ok      -> dos citas en la misma franja",
            "",
            "-- Validar leyendo NO alcanza: entre el SELECT y el INSERT cabe otra sesion.",
            "-- La unica defensa que no depende del tiempo es una restriccion:",
            "ALTER TABLE cita",
            "  ADD CONSTRAINT uq_cita_vet_franja UNIQUE (id_veterinario, fecha_hora);",
            "-- Ahora el segundo INSERT falla, sin importar el orden ni la velocidad.",
        ]),
        ("El bloqueo explicito y la actualizacion condicional", [
            "-- Opcion A: bloquear la fila y obligar a esperar",
            "BEGIN;",
            "SELECT stock FROM insumo WHERE id_insumo = 5 FOR UPDATE;",
            "UPDATE insumo SET stock = stock - 2 WHERE id_insumo = 5;",
            "COMMIT;",
            "",
            "-- Opcion B: sin bloqueo, poniendo la condicion DENTRO del UPDATE",
            "UPDATE insumo SET stock = stock - 2",
            "WHERE id_insumo = 5 AND stock >= 2;",
            "-- Si devuelve UPDATE 0, otro llego primero. Se comprueba, no se supone.",
        ]),
        ("Niveles de aislamiento: que anomalia tapa cada uno", [
            "SHOW transaction_isolation;      -- en PostgreSQL: read committed",
            "",
            "BEGIN ISOLATION LEVEL REPEATABLE READ;",
            "  -- la misma consulta devuelve lo mismo durante toda la transaccion",
            "COMMIT;",
            "",
            "BEGIN ISOLATION LEVEL SERIALIZABLE;",
            "  -- PostgreSQL detecta el conflicto y ABORTA una de las dos:",
            "  -- ERROR: could not serialize access due to read/write dependencies",
            "COMMIT;",
            "",
            "-- PostgreSQL no tiene READ UNCOMMITTED real: se comporta como READ COMMITTED.",
            "-- Y serializable no evita el error: obliga a REINTENTAR en la aplicacion.",
        ]),
    ],

    # ── Clase 11 · Verificacion del avance del PI ───────────────────────────
    11: [
        ("La bateria de verificacion del avance", [
            "-- 1. estan las 8 tablas del modelo?",
            "SELECT table_name FROM information_schema.tables",
            "WHERE table_schema = 'public' ORDER BY table_name;",
            "",
            "-- 2. tienen todas clave primaria?",
            "SELECT t.table_name",
            "FROM information_schema.tables t",
            "LEFT JOIN information_schema.table_constraints c",
            "       ON c.table_name = t.table_name AND c.constraint_type = 'PRIMARY KEY'",
            "WHERE t.table_schema = 'public' AND c.constraint_name IS NULL;",
            "-- cero filas = todas tienen PK",
        ]),
        ("Integridad y objetos de negocio, contados", [
            "-- 3. las claves foraneas declaradas",
            "SELECT tc.table_name, kcu.column_name, ccu.table_name AS referencia",
            "FROM information_schema.table_constraints tc",
            "JOIN information_schema.key_column_usage kcu",
            "     ON kcu.constraint_name = tc.constraint_name",
            "JOIN information_schema.constraint_column_usage ccu",
            "     ON ccu.constraint_name = tc.constraint_name",
            "WHERE tc.constraint_type = 'FOREIGN KEY'",
            "ORDER BY tc.table_name;",
            "",
            "-- 4. procedimientos, funciones y triggers que existen de verdad",
            "SELECT routine_name, routine_type FROM information_schema.routines",
            "WHERE routine_schema = 'public' ORDER BY routine_name;",
            "SELECT trigger_name, event_object_table FROM information_schema.triggers;",
        ]),
    ],

    # ── Clase 12 · Integracion app <-> BD ───────────────────────────────────
    12: [
        ("El contrato de la capa de API: siempre parametros ligados", [
            "-- La BD expone operaciones, no tablas. La aplicacion llama, no improvisa SQL.",
            "CREATE OR REPLACE FUNCTION api_agenda_del_dia(p_dia DATE)",
            "RETURNS TABLE (id_cita INT, hora TIMESTAMP, mascota VARCHAR, dueno VARCHAR)",
            "LANGUAGE sql",
            "STABLE",
            "AS $$",
            "  SELECT c.id_cita, c.fecha_hora, m.nombre, d.nombre",
            "  FROM cita c",
            "  JOIN mascota m ON m.id_mascota = c.id_mascota",
            "  JOIN dueno   d ON d.id_dueno   = m.id_dueno",
            "  WHERE c.fecha_hora >= p_dia AND c.fecha_hora < p_dia + 1",
            "  ORDER BY c.fecha_hora;",
            "$$;",
        ]),
        ("La inyeccion de SQL, explicada con las dos versiones", [
            "-- MAL: la aplicacion concatena lo que el usuario escribio",
            "--   \"SELECT * FROM dueno WHERE nombre = '\" + entrada + \"'\"",
            "-- Si entrada = 'x'; DROP TABLE cita; --",
            "-- el motor recibe dos sentencias y ejecuta las dos.",
            "",
            "-- BIEN: el valor viaja como PARAMETRO, nunca como texto de la sentencia",
            "PREPARE buscar_dueno (VARCHAR) AS",
            "  SELECT id_dueno, nombre, telefono FROM dueno WHERE nombre = $1;",
            "",
            "EXECUTE buscar_dueno('Ana Gomez');",
            "EXECUTE buscar_dueno('x''; DROP TABLE cita; --');   -- 0 filas, nada mas",
        ]),
    ],

    # ── Clase 13 · Analisis de casos reales (autonoma) ──────────────────────
    13: [
        ("Leer un plan de ejecucion ajeno", [
            "EXPLAIN (ANALYZE, BUFFERS)",
            "SELECT d.nombre, COUNT(c.id_cita) AS citas",
            "FROM dueno d",
            "JOIN mascota m ON m.id_dueno   = d.id_dueno",
            "JOIN cita    c ON c.id_mascota = m.id_mascota",
            "WHERE c.fecha_hora >= DATE '2026-01-01'",
            "GROUP BY d.id_dueno, d.nombre",
            "HAVING COUNT(c.id_cita) > 5;",
            "",
            "-- 1. el nodo mas costoso (cost mas alto), no el primero",
            "-- 2. Seq Scan sobre tabla grande con filtro selectivo -> falta indice",
            "-- 3. rows estimadas vs actual: si difieren 10x, ANALYZE la tabla",
            "-- 4. Nested Loop con muchas filas -> suele querer Hash Join",
        ]),
    ],
}
