# -*- coding: utf-8 -*-
"""Consulta de Pexels (en ingles) para cada lamina de viñetas que no tiene animacion.

Clave: comienzo del titulo de la lamina tal como lo arma el builder (antes del filtro de
anonimizacion), sin importar tildes ni mayusculas. Una consulta concreta trae una foto que
dice algo del tema; las que no estan aqui se buscan con el titulo y quedan anotadas en
`assets/pexels/_sin_curar.txt` para curarlas.
"""

FOTOS = {
    # Laminas de marco (todas las clases)
    "Objetivos de la clase": "students learning laptops classroom",
    "Objetivos de la sesión": "students learning laptops classroom",
    "Objetivos de la sesion": "students learning laptops classroom",
    "Encuadre de hoy": "notebook planning desk coffee",
    "Indicaciones": "students writing exam",
    # Arquitectura
    "Qué es arquitectura cloud": "cloud computing data center",
    "CloudLite App": "appointment booking app smartphone",
    "De dominio a arquitectura": "software architect whiteboard diagram",
    "IaaS · PaaS · SaaS": "cloud server infrastructure",
    "Cómo decidir para CloudLite": "team decision meeting laptop",
    "Responsabilidad compartida": "handshake technology partnership",
    "Plantilla ADR": "architecture decision document notebook",
    "La pila dibujada": "server rack layers",
    "VM vs contenedor": "shipping containers port",
    "Comprobar en un lab": "developer terminal laptop",
    "Dockerfile mínimo": "shipping container crane",
    "Construir, correr y verificar el contenedor": "developer running code terminal",
    "Monolito vs microservicios": "building blocks modular",
    "C4-lite": "architecture diagram sketch",
    "C4Container en Mermaid": "diagram on screen developer",
    "Distribuido implica fallos": "network cables server failure",
    "Amenazas que sí importan": "cyber security padlock",
    "Controles prácticos": "security key lock laptop",
    "Menor privilegio": "access control keycard door",
    "Ejercicio guiado": "students working laptops together",
    "Red lógica para el diagrama": "network switch cables",
    "Almacenamiento": "hard drives storage server",
    "Checklist del diagrama Deployment": "checklist clipboard",
    "El molde de Mermaid": "code editor screen",
    "CI/CD sin tarjeta": "assembly line automation",
    "YAML mínimo": "configuration code screen",
    "Monitoreo y optimización": "monitoring dashboard screens",
    "El pipeline del stub": "pipeline industrial pipes",
    "Costos sin factura real": "calculator budget spreadsheet",
    "Sostenibilidad": "green energy solar panels",
    "Errores frecuentes a corregir": "red pen correction paper",
    "Rendimiento sin stress-tool": "speedometer performance",
    "Preparación de presentación": "presenter speaking audience",
    "Escala para CloudLite": "growth chart scale",
    "Límites y costos": "money coins limit",
    "Cierre del curso": "graduation students celebration",
    # Programacion II
    "Abstracción y encapsulamiento": "capsule pills closeup",
    "Demo del dia": "laptop code live demo",
    "La interfaz List": "list notebook checklist",
    "Mapas y ventanas": "map compass desk",
    "getSource y otros escuchadores": "remote control buttons",
    "Cuándo NO usarlos": "stop sign road",
    "Nombres que se explican solos": "labels organized jars",
    # Bases de Datos II
    "El cliente: una clínica veterinaria": "veterinary clinic paper records",
    "Ciclo de vida de una cuenta": "user account login screen",
    "Como amarra con las clases vecinas": "puzzle pieces connected",
    "El molde de un caso de error": "test tubes laboratory",
    "La columna paso y la trampa": "warning sign trap",
    "Los 6 bloques del contrato": "contract signing document",
    "PROCEDURE o FUNCTION": "fork in the road choice",
    "La funcion de tarifas": "price tags veterinary",
    "Donde vive cada validacion": "layers of rock strata",
    "Plan de respaldo": "backup hard drive external",
    "Un plan, campo por campo": "blueprint plan detail",
    "La subconsulta correlacionada en el plan": "loop roller coaster",
    "Optimizar no cambia el resultado": "scale balance equal",
    "El antes y el despues del script": "before after comparison",
    "Los cinco indices, y la consulta": "book index pages",
    "Los cinco indices de hoy": "library catalog drawers",
    "El indice parcial": "highlighted pages book",
    "Particionar hoy de verdad": "filing cabinet drawers years",
    "El veredicto de particionamiento": "judge gavel decision",
    "La demo, en el orden": "laptop presentation demo",
    "Donde corre esto, y que no se puede medir": "laptop browser code",
    "sp_facturar en PL/pgSQL": "invoice receipt printing",
    "Por que el procedimiento no lleva COMMIT": "checkpoint barrier",
    "El contraste con Oracle": "two paths comparison",
    "fn_descontar_stock": "warehouse inventory shelves",
    "Donde corre esto, y por que el autocommit": "laptop database browser",
    "Como se ordena la sesion de hoy": "presentation schedule agenda",
    # Introduccion a la Ingenieria
    "Cuándo el problema dejó de ser la máquina": "vintage computer mainframe",
    "Colombia: dos datos locales": "hydroelectric dam",
    "La línea base": "stopwatch measurement",
    "Qué es la Ingeniería de Sistemas": "engineers team planning",
    "El proyecto del curso": "students project team table",
    "Cinco equipos": "five people team hands",
}
