# -*- coding: utf-8 -*-
"""Part 1: paths and class catalog for Arquitectura PI-first batch."""
from pathlib import Path

SLIDES_DIR = Path(r"G:\Mi unidad\Trabajos\Empleo\UNIAJ\Cursos\config\slides")
CURSO = Path(r"G:\Mi unidad\Trabajos\Empleo\UNIAJ\Cursos\Arquitectura de Sistemas Computacionales")

RAW = [
(1,"regular","Introduccion a arquitecturas cloud","Introduccion a arquitecturas cloud",
 "Diagnostico · CloudLite App · primer boceto",
 "Definir dominio CloudLite + 3-5 capacidades + problema en 2-3 frases",
 "Ficha PI: dominio, capacidades, actores y boceto C4 Context",
 "Padlet · Excalidraw / draw.io"),
(2,"autonoma","Modelos de servicio IaaS PaaS SaaS","Modelos de servicio: IaaS, PaaS, SaaS",
 "Actividad autonoma · ADR del PI",
 "Decidir modelo dominante IaaS/PaaS/SaaS para CloudLite + ADR",
 "ADR-001 decision de modelo de servicio + matriz del dominio",
 "Google Docs · draw.io"),
(3,"regular","Virtualizacion y contenedores","Virtualizacion y contenedores",
 "Lab Killercoda / Play with Docker → stub CloudLite",
 "Contenerizar un stub del servicio principal de CloudLite",
 "Dockerfile (+ compose opcional) + captura/enlace lab navegador",
 "Killercoda · Play with Docker"),
(4,"regular","Microservicios y arquitecturas distribuidas","Microservicios · Arquitecturas distribuidas",
 "C4 Componentes CloudLite",
 "Diagramar componentes/servicios CloudLite y sus contratos",
 "Diagrama C4 Container/Componentes v0.9 + 3 contratos API",
 "draw.io / diagrams.net"),
(5,"parcial","Parcial 1","Parcial 1","Solo evaluacion","Sin avance dirigido de PI","—","—"),
(6,"regular","Seguridad en la nube","Seguridad en la nube",
 "Amenazas y controles → seccion PI",
 "Modelo de amenazas minimo + controles para CloudLite",
 "Seccion Seguridad: 5 amenazas STRIDE-lite + controles + secretos",
 "Excalidraw · Google Docs"),
(7,"regular","Redes y almacenamiento cloud","Redes y almacenamiento cloud",
 "Diagrama de despliegue CloudLite",
 "Diagrama de despliegue: red, zonas, almacenamiento",
 "Deployment draw.io + eleccion de storage conceptual",
 "draw.io"),
(8,"regular","Monitoreo optimizacion y CI-CD","Monitoreo y optimizacion · CI/CD",
 "GitHub Actions + plan de observabilidad",
 "Workflow Actions build/test/simulate + metricas de monitoreo",
 ".github/workflows/ci.yml + seccion Monitoreo/CI del informe",
 "GitHub Actions · Google Docs"),
(9,"parcial","Parcial 2","Parcial 2","Solo evaluacion","Sin avance dirigido de PI","—","—"),
(10,"autonoma","Costos y sostenibilidad cloud","Costos y sostenibilidad cloud",
 "Actividad autonoma · seccion PI",
 "Estimacion cualitativa de costos + sostenibilidad",
 "Seccion Costos/Sostenibilidad (B/M/A + drivers)",
 "Google Docs"),
(11,"regular","Avance del proyecto final","Avance del proyecto final",
 "Checkpoint diagramas v1 CloudLite",
 "Integrar diagramas v1 + checklist de avance PI",
 "Paquete v1: C4 + Deployment + Dockerfile + Actions + informe 60%+",
 "draw.io · GitHub · Google Docs"),
(12,"regular","Pruebas de rendimiento y preparacion final",
 "Pruebas de rendimiento · Preparacion de presentacion final",
 "Metricas objetivo + ensayo de pitch PI",
 "Escenario de rendimiento + ensayo pitch 5-8 min",
 "Seccion Rendimiento + guion de pitch + paquete casi-final",
 "Google Docs · draw.io"),
(13,"autonoma","Escalabilidad automatica","Escalabilidad automatica",
 "Actividad autonoma · escenario de escala PI",
 "Documentar politica de autoescalado conceptual CloudLite",
 "Seccion Escalabilidad: triggers, limites, que escala y que no",
 "Google Docs · draw.io"),
(14,"parcial","Parcial 3","Parcial 3","Solo evaluacion","Sin trabajo dirigido nuevo de PI","—","—"),
(15,"autonoma","Presentacion del proyecto y cierre","Presentacion del proyecto + cierre",
 "Sustentacion PI CloudLite (autonoma)",
 "Sustentacion / entrega final del PI CloudLite App",
 "Paquete final + presentacion 5-8 min (ExamLab)",
 "Google Docs/Slides · diagramas · capturas"),
]

PARCIAL_FILE = {
5: "Parcial 1 - Cloud virtualizacion y distribuidos.docx",
9: "Parcial 2 - Seguridad redes monitoreo y CI-CD.docx",
14: "Parcial 3 - Rendimiento escalabilidad y cierre de proyecto.docx",
}
