# -*- coding: utf-8 -*-
from pathlib import Path
import json

out = Path(r"G:\Mi unidad\Trabajos\Empleo\UNIAJ\Cursos\.config\slides\arq_taller_data.py")

HERRAMIENTAS_DIA = {
    1: [
        {"name": "Padlet", "logo": "padlet.png", "note": "Rompe-hielo"},
        {"name": "draw.io", "logo": "drawio.png", "note": "C4 Context"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Boceto rapido"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Ficha PI"},
    ],
    2: [
        {"name": "Google Docs", "logo": "google_docs.png", "note": "ADR-001"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Matriz modelos"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Boceto"},
    ],
    3: [
        {"name": "Killercoda", "logo": "killercoda.png", "note": "Lab contenedores"},
        {"name": "Play with Docker", "logo": "play_with_docker.png", "note": "Sandbox"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Informe PI"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Nota arquitectura"},
    ],
    4: [
        {"name": "draw.io", "logo": "drawio.png", "note": "C4 Containers"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Boceto contratos"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Seccion PI"},
    ],
    6: [
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Amenazas"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Controles"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Seccion Seguridad"},
    ],
    7: [
        {"name": "draw.io", "logo": "drawio.png", "note": "Deployment"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Zonas"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Seccion Redes"},
    ],
    8: [
        {"name": "GitHub Actions", "logo": "github_actions.png", "note": "CI free"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Monitoreo"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Pipeline conceptual"},
    ],
    10: [
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Costos B/M/A"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Drivers"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Boceto"},
    ],
    11: [
        {"name": "draw.io", "logo": "drawio.png", "note": "Diagramas v1"},
        {"name": "GitHub Actions", "logo": "github_actions.png", "note": "Evidencia CI"},
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Informe 60%+"},
    ],
    12: [
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Pitch + metricas"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Arquitectura"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Storyboard"},
    ],
    13: [
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Politica escala"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Nota deploy"},
        {"name": "Excalidraw", "logo": "excalidraw.png", "note": "Triggers"},
    ],
    15: [
        {"name": "Google Docs", "logo": "google_docs.png", "note": "Paquete final"},
        {"name": "draw.io", "logo": "drawio.png", "note": "Diagramas"},
        {"name": "GitHub Actions", "logo": "github_actions.png", "note": "Evidencia CI"},
    ],
}

META = {
1: ("Definir dominio CloudLite medible + 3-5 capacidades + boceto C4 Context exportable.",
    ["@@Por que importa al PI:@@ sin dominio concreto no hay arquitectura que defender.",
     "La ficha + C4 Context son la semilla del informe y de todos los diagramas del semestre.",
     "Si el problema es vago (app de la universidad), el resto del PI se vuelve teatro.",
     "Hoy cierran frontera del sistema + actores externos; Containers internos = Clase 4."],
    ["Dominio con actor + dolor medible (no generico).",
     "3-5 capacidades en verbos de negocio.",
     "C4 Context: 1 caja sistema + >=2 actores + >=1 SaaS/sistema externo.",
     "Doc + PNG (o enlace) listos para Campus Virtual · domingo 23:59."],
    ["Equipo 2-3 (o individual). Elegir un dominio concreto.",
     "Sugeridos: AgendaU · BiblioLite · InventarioLab · TurnosClinica · EventosCampus.",
     "Plantilla ficha: DOMINIO · PROBLEMA · ACTORES · CAPACIDADES · FUERA DE ALCANCE.",
     "Herramienta: Excalidraw o draw.io (gratis en navegador)."],
    ["Quien sufre el problema y como lo miden?",
     "La caja grande es el sistema CloudLite (no un modulo interno)?",
     "Las flechas tienen verbo (reservar, notificar, autenticar)?",
     "Fuera de alcance esta escrito (que NO haran hoy)?"]),
2: ("Decidir modelo dominante para CloudLite y documentarlo en ADR-001.",
    ["@@Por que importa al PI:@@ el modelo IaaS/PaaS/SaaS define quien opera SO, runtime y costos.",
     "Sin ADR, el PI no puede justificar trade-offs en sustentacion ni en parciales.",
     "Restriccion del curso: gratis + navegador; no abrir IaaS con tarjeta."],
    ["Matriz IaaS/PaaS/SaaS vs capacidades del dominio.",
     "ADR con contexto, decision, >=2 alternativas y consecuencias +/-.",
     "Integrado a la seccion Modelo de servicio del informe.",
     "Entrega domingo 23:59 (clase autonoma)."],
    ["Partir de la ficha/C4 de Clase 1 (mismo dominio).",
     "MVP academico tipico: PaaS conceptual + SaaS satelite (auth/email).",
     "Documentar en Google Docs; diagrama opcional de responsabilidad compartida."],
    ["La decision nombra un modelo dominante (no un poco de todo)?",
     "Hay al menos dos alternativas descartadas con razon?",
     "Consecuencias incluyen operacion, costo y aprendizaje?"]),
3: ("Contenerizar un stub HTTP del servicio principal y dejar Dockerfile + captura.",
    ["@@Por que importa al PI:@@ CloudLite debe mostrar al menos un servicio contenerizado con evidencia.",
     "El contenedor es el puente entre el diagrama C4 y el despliegue realista (sin cloud de pago).",
     "Labs en navegador (Killercoda / Play with Docker): sin Docker Desktop obligatorio."],
    ["Dockerfile legible (imagen slim, EXPOSE, CMD).",
     "Stub responde en / o /health.",
     "Captura o enlace de sesion lab (o plan B si caduca).",
     "Seccion Contenedores del informe actualizada."],
    ["Elegir el servicio principal del C4 (API o web).",
     "Abrir Killercoda o Play with Docker; sesion temporal.",
     "Prohibido: copiar .env / API keys a la imagen."],
    ["El puerto expuesto coincide con el que documentan?",
     "Hay evidencia con timestamp (captura o enlace)?",
     "Secretos fuera de la imagen?"]),
4: ("Diagramar Containers CloudLite (2-5) + 3 contratos API minimos.",
    ["@@Por que importa al PI:@@ el C4 Containers es el mapa logico que luego alinea Deployment y CI.",
     "Anti-patron: 12 microservicios para 3 estudiantes = teatro, no arquitectura.",
     "Regla CloudLite: 2-5 cajas justificadas + contratos etiquetados."],
    ["Cada caja: nombre + responsabilidad + tech tentativa.",
     "Flechas con protocolo + verbo de negocio.",
     "3 contratos: in/out/errores (ej. 401/409).",
     "Export PNG + .drawio al paquete PI."],
    ["Partir del C4 Context (mismos nombres de sistema/actores).",
     "draw.io o Excalidraw; vista Containers (no solo Context).",
     "Contratos en Doc o notas junto al diagrama."],
    ["Hay 2-5 cajas (no 1 monolito innominado ni 12 microservicios)?",
     "Los nombres coincidiran luego con Deployment?",
     "Cada contrato tiene error de negocio (ej. 409 conflicto)?"]),
6: ("Modelo de amenazas minimo + controles + politica de secretos para CloudLite.",
    ["@@Por que importa al PI:@@ seguridad = amenazas del dominio + controles visibles.",
     "Si la API key esta en el Dockerfile, ya filtraron el secreto.",
     "STRIDE-lite: 5 amenazas concretas, no lista generica de internet."],
    ["5 amenazas del dominio (STRIDE-lite) con control y evidencia.",
     "Politica de secretos (media pagina).",
     "Seccion Seguridad 1-1.5 paginas en el informe.",
     "Controles reflejados en diagrama (HTTPS, trust boundary, etc.)."],
    ["Usar dominio y Containers ya definidos.",
     "Amenazas tipicas: secrets en imagen, API sin auth, logs con tokens, PII sin TLS.",
     "Herramientas: Excalidraw + Google Docs."],
    ["Cada amenaza tiene control + donde se ve en el diagrama?",
     "Secretos en Settings/Actions, no en Dockerfile?",
     "Least privilege aparece aunque sea narrado?"]),
7: ("Deployment CloudLite: zonas + storage conceptual etiquetado.",
    ["@@Por que importa al PI:@@ sin zonas, el Deployment no demuestra fronteras de confianza.",
     "Si la BD esta en zona publica, el diagrama ya fallo.",
     "Nombres del Deployment deben = nombres del C4 Containers."],
    ["Zonas Publica / Privada / Datos (o equivalentes claros).",
     "Puertos y almacenes etiquetados.",
     "Eleccion de storage (DB + object si aplica) justificada.",
     "Seccion Redes y almacenamiento en el informe."],
    ["Cliente -> edge -> app -> datos.",
     "Sin inventar subnets AWS; trust boundaries si.",
     "draw.io como herramienta principal."],
    ["La BD esta en zona de datos/privada?",
     "Mismos nombres que el C4?",
     "Object storage solo si el dominio lo necesita?"]),
8: ("Workflow Actions (build/test + deploy simulado) + plan de monitoreo.",
    ["@@Por que importa al PI:@@ CI que solo hace echo success no es CI.",
     "GitHub Actions free = evidencia de build/test sin tarjeta.",
     "Observabilidad: 4-6 metricas atadas al dominio (golden signals-lite)."],
    [".github/workflows/ci.yml con pasos reales (o YAML serio + explicacion).",
     "Deploy simulado (artifact/echo) documentado.",
     "4-6 metricas (latencia, errores, trafico, saturacion).",
     "Secciones CI/CD y Monitoreo en el informe."],
    ["Repo free + stub de Clase 3 (o minimo).",
     "Secrets en Settings; nunca en el YAML en claro.",
     "Captura de run verde o YAML + explicacion si no corre."],
    ["Hay build o test real (no solo echo vacio)?",
     "Secrets fuera del repositorio?",
     "Metricas con umbral u objetivo narrado?"]),
10: ("Seccion Costos/Sostenibilidad del PI con tabla por componente.",
    ["@@Por que importa al PI:@@ lo mas caro suele ser lo que dejan encendido sin usar.",
     "Costo cualitativo B/M/A es aceptable: no inventar precios USD de cloud de pago.",
     "Sostenibilidad: slim + labs temporales + right-sizing."],
    ["Tabla componente -> driver -> B/M/A -> apalancamiento.",
     ">=3 acciones de sostenibilidad verificables.",
     "1 pagina integrada al informe.",
     "Entrega domingo 23:59 (autonoma)."],
    ["Componentes: API, DB, object, CI, edge.",
     "Drivers: idle, egress, storage, minutos CI.",
     "Google Docs como herramienta principal."],
    ["Cada fila tiene driver (no solo caro)?",
     "Las 3 acciones son verificables en el PI?",
     "Evitaron inventar facturas de AWS/GCP?"]),
11: ("Paquete v1 CloudLite: diagramas + Dockerfile + Actions + informe 60%+.",
    ["@@Por que importa al PI:@@ checkpoint v1 = integrar evidencias; no es sustentacion ni Parcial 3.",
     "Si C4 y Deployment no comparten nombres, el PI esta roto.",
     "Hoy cierran huecos con checklist viva + backlog a Clase 12."],
    ["Checklist si/no/parcial con enlaces a evidencias.",
     "Nombres unificados C4 <-> Deployment.",
     "ZIP/repo con evidencias + backlog 5 items.",
     "Feedback docente incorporado o anotado."],
    ["Revisar: dominio, ADR, C4, Deployment, Dockerfile, Actions, Seguridad, Costos.",
     "Demo corta por equipo si el tiempo alcanza."],
    ["Cada si tiene enlace o ruta de archivo?",
     "Hay backlog priorizado (no lista infinita)?",
     "Anti-patrones (teatro microservicios / secretos / CI vacio) marcados?"]),
12: ("Escenario de rendimiento + ensayo pitch + paquete casi-final.",
    ["@@Por que importa al PI:@@ sin metrica objetivo, rapido es opinion — no arquitectura.",
     "Ensayo de pitch 5-8 min reduce riesgo en la sustentacion (Clase 15).",
     "Parcial 3 es Clase 14 (solo evaluacion); hoy preparan evidencias."],
    ["Escenario de carga con 3 metricas + bottleneck.",
     "Pitch cronometrado 5-8 min (todos hablan).",
     "Backlog de Clase 11 cerrado o residual explicito.",
     "Paquete casi-final ordenado."],
    ["Pico del dominio (ej. inicio de semestre / dia de citas).",
     "Demo permitida: diagrama + captura lab/Actions — no K8s de pago."],
    ["p95 / error rate / RPS tienen numero u orden de magnitud?",
     "Bottleneck nombrado (DB/auth/storage)?",
     "Guion de pitch con tiempos por seccion?"]),
13: ("Seccion Escalabilidad: triggers, min/max, que escala y que no.",
    ["@@Por que importa al PI:@@ escalar la API no escala sola la base de datos.",
     "Politica de autoescalado conceptual = evidencia de diseno (sin cloud de pago).",
     "Definir que NO escala evita promesas imposibles en sustentacion."],
    ["Horizontal vs vertical aplicado al dominio.",
     ">=2 triggers + min/max + cooldown narrado.",
     "Lo que NO escala justificado (ej. DB primaria).",
     "Nota opcional en Deployment + entrega domingo 23:59."],
    ["Plantilla: componente, tipo, trigger up/down, min/max, cooldown.",
     "Impacto en costo cualitativo (enlace a Clase 10)."],
    ["Triggers medibles (RPS, p95, cola)?",
     "Hay techo (max) para no escalar infinito?",
     "DB/sesion sticky justificados como no-escalables?"]),
15: ("Entregar paquete final + pitch 5-8 min + Q&A escrito.",
    ["@@Por que importa al PI:@@ sustentacion = evidencias + decisiones, no tour de logos.",
     "PI 20% Corte 3 no sustituye el Parcial 3 (ya ocurrio en Clase 14).",
     "Paquete final ordenado facilita la calificacion con rubrica."],
    ["ZIP/PDF en Campus Virtual con diagramas + lab + CI + informe.",
     "Pitch 5-8 min con todos los integrantes.",
     "Q&A escrito 3+3 + reflexion 1/2 pagina.",
     "Autoevaluacion breve del proceso."],
    ["Orden del pitch: problema -> arquitectura -> contenedor/CI -> seguridad/costos/escala -> Q&A.",
     "Sin AWS/GCP obligatorio."],
    ["Evidencias minimas presentes (diagramas + lab + CI + decisiones)?",
     "Tiempos del pitch ensayados?",
     "PI y Parcial 3 no se confunden en el discurso?"]),
}

SOLUCION = {
1: dict(titulo="Solucion Taller Clase 1 — Ficha + C4 Context CloudLite",
    resumen="Ejemplo aceptable (AgendaU). Otros dominios validos si cumplen criterios.",
    pasos=["Equipo 2-3. Dominio: AgendaU (tutorias estudiante-docente).",
           "Problema: estudiantes pierden turnos por doble agenda y recordatorios debiles.",
           "Actores: Estudiante, Tutor, CloudLite App; SaaS: correo/calendario.",
           "Capacidades: reservar, cancelar, recordar, ver disponibilidad.",
           "C4 Context exportable PNG + .drawio."],
    ejemplo=["DOMINIO: AgendaU",
             "PROBLEMA: perdida de turnos por solapamientos y falta de recordatorio.",
             "ACTORES: Estudiante, Tutor; externo: email SaaS.",
             "CAPACIDADES: reservar, cancelar, listar disponibilidad, notificar.",
             "FUERA DE ALCANCE: pagos, videollamada, app nativa.",
             "C4: CloudLite App <-HTTPS-> personas; CloudLite ->SMTP-> Email SaaS."],
    rubrica=["Dominio concreto (2)", "Capacidades+actores (2)", "C4 correcto (3)", "Evidencia+entrega (2)", "Fuera de alcance (1)"],
    errores=["Rechazar dominio vago sin actor/metrica.", "No pedir Containers internos hoy.", "C4 sin flechas."]),
2: dict(titulo="Solucion Taller Clase 2 — ADR-001",
    resumen="Decision tipica: PaaS conceptual + SaaS satelite.",
    pasos=["Matriz IaaS/PaaS/SaaS vs capacidades.",
           "Decision: PaaS conceptual API/web; SaaS email/auth.",
           "Alternativas: IaaS puro (tarjeta/ops); SaaS total (poco control).",
           "ADR-001 en Docs + seccion informe."],
    ejemplo=["Titulo: Modelo de servicio dominante CloudLite",
             "Decision: PaaS conceptual + contenedores lab; SaaS email",
             "Estado: Aceptada"],
    rubrica=["Matriz (2)", "Decision (2)", "Alternativas (3)", "Consecuencias (2)", "Informe (1)"],
    errores=["Un poco de todo sin dominante.", "AWS con tarjeta como requisito."]),
3: dict(titulo="Solucion Taller Clase 3 — Stub contenerizado",
    resumen="Dockerfile minimo + evidencia lab navegador.",
    pasos=["Servicio api-reservas.", "Dockerfile slim+EXPOSE+CMD.", "Stub /health 200.", "Captura timestamp + seccion Contenedores."],
    ejemplo=["FROM python:3.12-slim", "WORKDIR /app", "COPY app.py .", "EXPOSE 8080", 'CMD ["python","app.py"]'],
    rubrica=["Dockerfile (3)", "HTTP stub (2)", "Evidencia (3)", "Sin secretos (1)", "Informe (1)"],
    errores=["Keys en imagen.", "Sin captura ni archivo."]),
4: dict(titulo="Solucion Taller Clase 4 — C4 Containers + contratos",
    resumen="Ejemplo 3 contenedores: web, api, db.",
    pasos=["Containers WebApp, ApiReservas, DbAgenda.",
           "Flechas HTTPS/SQL/SMTP etiquetadas.",
           "3 contratos API con errores.",
           "Export PNG+.drawio."],
    ejemplo=["POST /api/reservas — 401/409", "DELETE /api/reservas/{id} — 404/403", "GET /api/disponibilidad — 400"],
    rubrica=["2-5 cajas (3)", "Flechas (2)", "Contratos (3)", "Export+informe (2)"],
    errores=["12 microservicios teatro.", "Nombres distintos al Context."]),
6: dict(titulo="Solucion Taller Clase 6 — STRIDE-lite",
    resumen="5 amenazas del dominio + politica secretos.",
    pasos=["5 amenazas STRIDE-lite.", "Control en diagrama.", "Politica secretos media pagina.", "Seccion Seguridad 1-1.5 pag."],
    ejemplo=["Spoofing->tokens+HTTPS", "Tampering->authz+audit", "Disclosure->TLS", "DoS-lite->rate-limit", "Elevation->least privilege"],
    rubrica=["5 amenazas (3)", "Control+evidencia (3)", "Politica secretos (2)", "Informe (2)"],
    errores=["Lista generica.", "Keys en imagen/README."]),
7: dict(titulo="Solucion Taller Clase 7 — Deployment zonas",
    resumen="Publica/Privada/Datos; DB no publica.",
    pasos=["Zonas + colocacion servicios.", "Puertos etiquetados.", "Storage justificado.", "Nombres=C4."],
    ejemplo=["Publica: WebApp", "Privada: ApiReservas", "Datos: DbAgenda", "Object opcional PDF"],
    rubrica=["Zonas (3)", "DB no publica (2)", "Nombres=C4 (2)", "Storage (2)", "Informe (1)"],
    errores=["DB en zona publica.", "Subnets AWS inventadas."]),
8: dict(titulo="Solucion Taller Clase 8 — Actions + monitoreo",
    resumen="ci.yml build/test + deploy simulado + 4 metricas.",
    pasos=["Repo+stub.", "ci.yml checkout->build/test->artifact.", "4-6 metricas golden signals-lite.", "Captura o YAML+explicacion."],
    ejemplo=["name: ci", "on: [push]", "jobs.build.runs-on: ubuntu-latest", "steps: checkout + build-and-test + deploy-simulated"],
    rubrica=["YAML (3)", "Build/test serio (2)", "Metricas (3)", "Evidencia (2)"],
    errores=["Solo echo vacio.", "Secrets en claro."]),
10: dict(titulo="Solucion Taller Clase 10 — Costos B/M/A",
    resumen="Tabla cualitativa + 3 acciones sostenibilidad.",
    pasos=["Filas API/DB/Object/CI/Edge.", "Drivers idle/egress/storage/CI.", "3 acciones slim/labs/right-size.", "1 pagina informe."],
    ejemplo=["API idle Medio", "DB storage Medio", "CI minutos Bajo", "Acciones: slim + labs off + right-size"],
    rubrica=["Tabla (4)", "3 acciones (3)", "Sin USD inventados (2)", "Integrado (1)"],
    errores=["Factura AWS inventada.", "Sera barato sin tabla."]),
11: dict(titulo="Solucion Taller Clase 11 — Checkpoint v1",
    resumen="Checklist con enlaces + backlog 5.",
    pasos=["Marcar si/no/parcial con enlaces.", "Unificar nombres.", "ZIP/repo + backlog top-5."],
    ejemplo=["C4 OK", "Deployment Parcial (renombrar)", "Actions Parcial (falta test)", "Backlog: test CI, secretos en diagrama, p95"],
    rubrica=["Checklist+evidencia (4)", "Nombres (2)", "Paquete (2)", "Backlog (2)"],
    errores=["Todo si sin enlaces.", "Tratar como sustentacion final."]),
12: dict(titulo="Solucion Taller Clase 12 — Rendimiento + pitch",
    resumen="Escenario pico + guion pitch 5-8 min.",
    pasos=["Escenario con 3 metricas + bottleneck.", "Ensayo pitch con tiempos.", "Cerrar backlog."],
    ejemplo=["RPS pico 50; p95 800ms; error 1%", "Bottleneck: disponibilidad DB", "Pitch: 1+2+1+1+1-2 min"],
    rubrica=["Escenario+metricas (3)", "Bottleneck (2)", "Pitch (3)", "Paquete (2)"],
    errores=["Rapido sin numeros.", "Load test de pago obligatorio."]),
13: dict(titulo="Solucion Taller Clase 13 — Autoescalado",
    resumen="API horizontal; DB no escala igual.",
    pasos=["Politica API min/max/triggers.", "NO escala: DB primaria.", "Nota costo.", "Seccion Escalabilidad."],
    ejemplo=["ApiReservas H RPS>40 min1 max4", "DbAgenda no auto 1/1"],
    rubrica=["Politica (4)", "NO escala (3)", "Costo (2)", "Entrega (1)"],
    errores=["Escalar DB=API.", "Sin techo max."]),
15: dict(titulo="Solucion Taller Clase 15 — Paquete + sustentacion",
    resumen="Checklist empaquetado + orden pitch.",
    pasos=["ZIP completo.", "Pitch 5-8 min.", "Q&A 3+3 + reflexion."],
    ejemplo=["/informe.pdf", "/diagramas/*.png", "/lab/Dockerfile+captura", "/ci/ci.yml+run.png", "/anexos/adr+qna"],
    rubrica=["Paquete (4)", "Pitch (3)", "Q&A+reflexion (2)", "PI!=P3 (1)"],
    errores=["Tour de logos.", "Falta lab o CI."]),
}

def accent(s: str) -> str:
    reps = [
        ("Por que", "Por qué"), ("seccion", "sección"), ("Seccion", "Sección"),
        ("autonoma", "autónoma"), ("decision", "decisión"), ("Decision", "Decisión"),
        ("Solucion", "Solución"), ("solucion", "solución"),
        ("metrica", "métrica"), ("Metricas", "Métricas"), ("metricas", "métricas"),
        ("pagina", "página"), ("rubrica", "rúbrica"), ("sesion", "sesión"),
        ("validos", "válidos"), ("tipico", "típico"), ("academico", "académico"),
        ("satelite", "satélite"), ("minimos", "mínimos"), ("minimo", "mínimo"),
        ("logico", "lógico"), ("Anti-patron", "Anti-patrón"), ("patron:", "patrón:"),
        ("generico", "genérico"), ("Politica", "Política"), ("politica", "política"),
        ("Publica", "Pública"), ("publica", "pública"), ("eleccion", "elección"),
        ("trafico", "tráfico"), ("explicacion", "explicación"), ("vacio", "vacío"),
        ("calificacion", "calificación"), ("reflexion", "reflexión"),
        ("autoevaluacion", "autoevaluación"), ("diseno", "diseño"),
        ("sustentacion", "sustentación"), ("evaluacion", "evaluación"),
        ("rapido", "rápido"), ("mas caro", "más caro"), ("debiles", "débiles"),
        ("tutorias", "tutorías"), ("perdida", "pérdida"), ("Titulo", "Título"),
        ("Quien ", "Quién "), ("quien ", "quién "), ("esta escrito", "está escrito"),
        ("esta en", "está en"), ("fallo.", "falló."), ("modulo", "módulo"),
        ("restriccion", "restricción"), ("operacion", "operación"), ("razon", "razón"),
        ("coincidiran", "coincidirán"), ("numer", "númer"), ("explicito", "explícito"),
        ("colocacion", "colocación"), ("ocurrido", "ocurrido"),
        ("Boceto rapido", "Boceto rápido"), ("Seccion PI", "Sección PI"),
        ("Seccion Seguridad", "Sección Seguridad"), ("Seccion Redes", "Sección Redes"),
        ("Pitch + metricas", "Pitch + métricas"), ("Politica escala", "Política escala"),
    ]
    for a, b in reps:
        s = s.replace(a, b)
    return s

TALLER_BLOQUE = {}
for n, (obj, ctx, crit, esc, pistas) in META.items():
    TALLER_BLOQUE[n] = {
        "contexto": [accent(x) for x in ctx],
        "objetivo": accent(obj),
        "criterios": [accent(x) for x in crit],
        "escenario": [accent(x) for x in esc],
        "pistas": ["□ " + accent(p) for p in pistas],
    }

for n, sol in SOLUCION.items():
    for k, v in list(sol.items()):
        if isinstance(v, list):
            sol[k] = [accent(x) for x in v]
        else:
            sol[k] = accent(v)

def emit(obj, indent=0):
    sp = " " * indent
    if isinstance(obj, dict):
        lines = ["{\n"]
        for k, v in obj.items():
            lines.append(f"{sp}    {k!r}: {emit(v, indent+4)},\n")
        lines.append(f"{sp}}}")
        return "".join(lines)
    if isinstance(obj, list):
        if not obj:
            return "[]"
        lines = ["[\n"]
        for item in obj:
            lines.append(f"{sp}    {emit(item, indent+4)},\n")
        lines.append(f"{sp}]")
        return "".join(lines)
    return repr(obj)

header = '# -*- coding: utf-8 -*-\n"""Bloque Taller ampliado + soluciones (PRIVADO) — Arquitectura / CloudLite."""\n\n'
body = header
body += "HERRAMIENTAS_DIA = " + emit(HERRAMIENTAS_DIA) + "\n\n"
body += "TALLER_BLOQUE = " + emit(TALLER_BLOQUE) + "\n\n"
body += "SOLUCION = " + emit(SOLUCION) + "\n"
out.write_text(body, encoding="utf-8")
print("OK", out, out.stat().st_size)
