# -*- coding: utf-8 -*-
"""Contenido de los 12 parciales UNIAJC 2026-2 (4 cursos x 3 cortes).

Regla de cobertura (obligatoria):
  - Solo clases con fecha en la ventana del corte Y fecha_clase <= fecha_parcial.
  - En BD II / Arquitectura: P2 = clases 6-9 (NO 10); P3 = clases 11-14 (NO 15).
  - Clase 1: se evalua el arranque tematico (no la logistica de Presentacion del curso).
  - Formato en portada: «Clase N · DD/MM · Tema».
  - Día de parcial = solo evaluación: la cobertura lista los temas en la clase
    donde se impartieron (no inventa tema técnico en la fila del parcial).
"""
from __future__ import annotations

ROOT = r"G:\Mi unidad\Trabajos\Empleo\UNIAJ\Cursos"


def _tema(n: int, fecha_dd_mm: str, tema: str) -> str:
    return f"Clase {n} · {fecha_dd_mm} · {tema}"


def _meta(**kw):
    return kw


def _sec(titulo, pts, items, intro=""):
    return {"titulo": titulo, "pts": pts, "items": items, "intro": intro}


PROG2_P1 = {
    "meta": _meta(
        curso_dir='Programacion II',
        asignatura='Programación II',
        codigo='FI303204',
        grupo='341C',
        periodo='2026-2',
        horario='Miércoles 20:00 – 22:00',
        n=1,
        corte=1,
        valor_corte='10% del Corte 1 (30%)',
        fecha='09/09/2026',
        clase=5,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 1 — POO, colecciones e interfaces GUI',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Verdadero / Falso — 20 pts',
 'C. Desarrollo conceptual — 25 pts',
 'D. Práctica (Java / GUI) — 35 pts'],
        archivo='Parcial 1 - POO colecciones e interfaces GUI',
        cobertura='Corte 1 · Únicamente clases con fecha <= 09/09/2026 (Clases 1-5):',
        temas=[
            _tema(1, '12/08', 'Introducción a POO'),
            _tema(2, '19/08', 'Colecciones dinámicas ArrayList'),
            _tema(3, '26/08', 'Pilas y colas'),
            _tema(4, '02/09', 'Mapas y conjuntos · Interfaces gráficas GUI'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'c',
             'id': 'A1',
             'nota': 'Polimorfismo: misma interfaz, comportamientos distintos.',
             'opciones': ['a) Encapsulamiento', 'b) Herencia', 'c) Polimorfismo', 'd) Abstracción'],
             'pregunta': 'En POO, ¿qué principio permite que una misma operación se comporte de '
                         'forma distinta según el tipo concreto del objeto?',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Tiene tamaño fijo al crearse, igual que un arreglo primitivo',
                          'b) Crece dinámicamente y permite acceso por índice',
                          'c) Solo almacena tipos primitivos',
                          'd) No permite duplicados'],
             'pregunta': '¿Cuál es una característica correcta de ArrayList en Java?',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) FIFO', 'b) LIFO', 'c) Aleatoria', 'd) Por prioridad'],
             'pregunta': 'Una pila (Stack) opera preferentemente con la política:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) JLabel / Label',
                          'b) JTextField / TextField',
                          'c) JTable',
                          'd) JProgressBar'],
             'pregunta': 'En una interfaz gráfica Swing/JavaFX típica de clase, el componente más '
                         'adecuado para capturar un texto corto del usuario es:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': 'Indique V o F y justifique en una línea.',
  'items': [{'clave': 'F',
             'enunciado': 'Un HashSet garantiza el orden de inserción de sus elementos.',
             'id': 'B1',
             'justificacion': 'HashSet no garantiza orden; LinkedHashSet sí mantiene orden de '
                              'inserción.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'Una cola (Queue) procesa primero el elemento que llegó primero (FIFO).',
             'id': 'B2',
             'justificacion': 'Definición estándar de cola.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'En un Map, cada clave puede asociarse a lo sumo a un valor (en un '
                          'instante dado).',
             'id': 'B3',
             'justificacion': 'Modelo clave→valor; la clave es única.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'El encapsulamiento consiste en exponer todos los atributos como public '
                          'para facilitar el acceso.',
             'id': 'B4',
             'justificacion': 'Encapsulamiento oculta estado interno y expone acceso controlado.',
             'pts': 5,
             'tipo': 'vf'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Verdadero / Falso'},
 {'intro': '',
  'items': [{'enunciado': 'Compare ArrayList, HashMap y HashSet. Indique para cada uno: (1) qué '
                          'almacena, (2) si permite duplicados y (3) un caso de uso del Proyecto '
                          'Integrador / dominio académico.',
             'id': 'C1',
             'lineas': 5,
             'pts': 12,
             'solucion': ['ArrayList: secuencia indexada; permite duplicados; ej. lista de '
                          'pacientes/mascotas.',
                          'HashMap: pares clave-valor; claves únicas; ej. id→objeto, '
                          'código→precio.',
                          'HashSet: conjunto sin duplicados; no indexado; ej. etiquetas únicas, '
                          'ids ya procesados.',
                          'Rúbrica: 4 pts por estructura correcta + 4 pts casos de uso + 4 pts '
                          'claridad.'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Explique con un ejemplo breve cuándo usaría una pila y cuándo una cola '
                          'en una aplicación con interfaz gráfica (por ejemplo, deshacer acciones '
                          'vs. atención de turnos).',
             'id': 'C2',
             'lineas': 5,
             'pts': 13,
             'solucion': ['Pila: Ctrl+Z / historial de pantallas (LIFO).',
                          'Cola: turnos de atención, cola de eventos a procesar (FIFO).',
                          'Rúbrica: 6 pts ejemplo pila + 6 pts ejemplo cola + 1 pt redacción.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Desarrollo conceptual'},
 {'intro': '',
  'items': [{'enunciado': 'Diseñe (en código o pseudocódigo Java claro) una clase Producto con '
                          'atributos encapsulados (codigo, nombre, precio) y un '
                          'ArrayList<Producto> que permita: agregar, buscar por código y listar.',
             'id': 'D1',
             'lineas': 8,
             'pts': 20,
             'requerimientos': ['Constructores / getters-setters o métodos equivalentes.',
                                'Método buscarPorCodigo(String) que retorne el producto o '
                                'null/Optional.',
                                'Indique brevemente qué componentes GUI usaría para capturar datos '
                                'y mostrar el listado (sin implementar toda la GUI).'],
             'solucion': ['Clase Producto con private + getters/setters (6 pts).',
                          'Gestión con ArrayList: add, for/stream buscar, listar (8 pts).',
                          'GUI: JTextField/JButton para captura; JTextArea o JTable para listado '
                          '(6 pts).'],
             'tipo': 'practica'},
            {'codigo': 'Map<String,Integer> stock = ...;\n'
                       'int contador = 0;\n'
                       '// complete aquí\n'
                       'System.out.println(contador);',
             'enunciado': 'Dado el siguiente fragmento incompleto, complete la lógica para contar '
                          'cuántas claves de un Map<String,Integer> tienen valor mayor que 10:',
             'id': 'D2',
             'lineas': 4,
             'pts': 15,
             'solucion': ['for (Integer v : stock.values()) if (v != null && v > 10) contador++;',
                          'o entrySet/stream filter. 15 pts si correcto; 8 si idea parcial.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Práctica (Java / GUI)'}],
}

PROG2_P2 = {
    "meta": _meta(
        curso_dir='Programacion II',
        asignatura='Programación II',
        codigo='FI303204',
        grupo='341C',
        periodo='2026-2',
        horario='Miércoles 20:00 – 22:00',
        n=2,
        corte=2,
        valor_corte='10% del Corte 2 (30%)',
        fecha='14/10/2026',
        clase=10,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 2 — Eventos, patrones, QA y persistencia',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Emparejamiento — 20 pts',
 'C. Desarrollo — 25 pts',
 'D. Práctica (eventos / archivos) — 35 pts'],
        archivo='Parcial 2 - Eventos patrones QA y persistencia',
        cobertura=('Corte 2 · Únicamente clases con fecha <= 14/10/2026 en la ventana del corte '
 '(Clases 6-10). No evalúa POO/ArrayList/GUI del Corte 1:'),
        temas=[
            _tema(6, '16/09', 'Eventos y controladores'),
            _tema(7, '23/09', 'Patrones de diseño'),
            _tema(8, '30/09', 'Documentación y QA'),
            _tema(9, '07/10', 'Refactorización con IA · Persistencia de archivos'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Solo herencia múltiple',
                          'b) Eventos y controladores (listeners / handlers)',
                          'c) Serialización binaria obligatoria',
                          'd) Compilación JIT'],
             'pregunta': 'En una GUI, el patrón de separación típico donde la vista dispara '
                         'acciones y un controlador responde se relaciona con:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Crear muchas instancias idénticas',
                          'b) Garantizar una única instancia con acceso global controlado',
                          'c) Separar interfaz de implementación de red',
                          'd) Ordenar colecciones'],
             'pregunta': 'El patrón Singleton busca:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) No comentar nunca el código',
                          'b) Pruebas, criterios de aceptación y documentación clara de métodos '
                          'públicos',
                          'c) Dejar warnings sin revisar',
                          'd) Duplicar lógica en cada clase'],
             'pregunta': 'Una buena práctica de QA / documentación de código incluye:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Solo System.out.println en consola',
                          'b) Lectura/escritura con flujos (Files/BufferedWriter) serializando '
                          'campos',
                          'c) Usar únicamente variables static',
                          'd) Compilar a bytecode a mano'],
             'pregunta': 'Para persistir una lista de objetos en un archivo de texto/CSV en Java, '
                         'una opción válida del corte es:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': '1-c, 2-b, 3-a, 4-d (5 pts c/u)',
             'col_a': ['1) Observer / Listener',
                       '2) MVC (idea)',
                       '3) Refactorización',
                       '4) Factory (idea)'],
             'col_b': ['a) Mejora estructura del código sin cambiar el comportamiento observable',
                       'b) Separa modelo, vista y control de la interacción',
                       'c) Reacciona a un evento (clic, cambio) cuando ocurre',
                       'd) Centraliza la creación de objetos según un criterio'],
             'id': 'B1',
             'instruccion': 'Empareje el concepto (Columna A) con su descripción (Columna B).',
             'pts': 20,
             'tipo': 'match'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Emparejamiento'},
 {'intro': '',
  'items': [{'enunciado': 'Describa un flujo de evento en GUI: componente → evento → '
                          'listener/controlador → actualización de modelo/vista. Use un ejemplo '
                          '(botón Guardar).',
             'id': 'C1',
             'lineas': 5,
             'pts': 12,
             'solucion': ['Botón genera ActionEvent; listener ejecuta guardar(); valida modelo; '
                          'persiste; refresca vista.',
                          'Rúbrica: secuencia completa 8 pts + ejemplo coherente 4 pts.'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Indique 3 criterios para aceptar una refactorización asistida por IA '
                          '(qué revisar antes de fusionar el cambio).',
             'id': 'C2',
             'lineas': 4,
             'pts': 13,
             'solucion': ['Compila/pruebas pasan; comportamiento preservado; estilo legible; sin '
                          'secretos; cambios mínimos justificados.',
                          'Rúbrica: 4 pts por criterio válido (máx 12) + 1 pt claridad.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Desarrollo'},
 {'intro': '',
  'items': [{'enunciado': 'Escriba un método Java (o pseudocódigo estricto) '
                          'guardarProductos(List<Producto> lista, Path archivo) que escriba '
                          'codigo;nombre;precio por línea, y otro cargarProductos que reconstruya '
                          'la lista.',
             'id': 'D1',
             'lineas': 8,
             'pts': 20,
             'requerimientos': ['Manejo básico de IOException (try/catch o throws).',
                                'Indique qué validaciones mínimas haría al cargar (línea mal '
                                'formada).'],
             'solucion': ['Escritura con BufferedWriter/Files.writeString línea a línea (8 pts).',
                          "Lectura split(';') y parseo (8 pts).",
                          'Validación campos/NumberFormat (4 pts).'],
             'tipo': 'practica'},
            {'enunciado': 'Proponga (texto + bosquejo) cómo conectaría un botón «Exportar» de la '
                          'GUI con el método de persistencia, sin bloquear indefinidamente la idea '
                          'de controlador.',
             'id': 'D2',
             'lineas': 5,
             'pts': 15,
             'solucion': ['Listener del botón llama al servicio/controlador exportar(); este '
                          'invoca guardarProductos; muestra mensaje éxito/error.',
                          'Rúbrica: separación vista/control 8 pts + manejo error 7 pts.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Práctica'}],
}

PROG2_P3 = {
    "meta": _meta(
        curso_dir='Programacion II',
        asignatura='Programación II',
        codigo='FI303204',
        grupo='341C',
        periodo='2026-2',
        horario='Miércoles 20:00 – 22:00',
        n=3,
        corte=3,
        valor_corte='15% del Corte 3 (40%)',
        fecha='18/11/2026',
        clase=15,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 3 — Integración, excepciones y cierre de proyecto',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Verdadero / Falso — 20 pts',
 'C. Caso de integración — 25 pts',
 'D. Práctica (excepciones / revisión) — 35 pts'],
        archivo='Parcial 3 - Integracion excepciones y cierre de proyecto',
        cobertura=('Corte 3 · Únicamente clases con fecha <= 18/11/2026 en la ventana del corte '
 '(Clases 11-15):'),
        temas=[
            _tema(11, '21/10', 'Revisión de código cruzada'),
            _tema(12, '28/10', 'Integración de módulos'),
            _tema(13, '04/11', 'Control de excepciones'),
            _tema(14, '11/11', 'Preparación presentación final · Evaluación de proyectos + cierre'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Reemplazar por completo las pruebas',
                          'b) Detectar defectos, mejorar calidad y compartir criterio técnico',
                          'c) Eliminar la documentación',
                          'd) Evitar el control de versiones'],
             'pregunta': 'Una revisión de código cruzada (peer review) busca principalmente:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A2',
             'opciones': ['a) Que las interfaces entre módulos no coincidan (contratos rotos)',
                          'b) Que Java deje de ser tipado',
                          'c) Que el compilador ignore sintaxis',
                          'd) Que ArrayList se convierta en Map automáticamente'],
             'pregunta': 'Al integrar módulos, un riesgo frecuente es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Error de hardware irreversible',
                          'b) Excepción comprobada (checked)',
                          'c) Anotación de compilación',
                          'd) Tipo primitivo'],
             'pregunta': 'checked vs unchecked en Java (idea del corte): IOException es '
                         'típicamente:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Ocultar los requisitos incumplidos sin mención',
                          'b) Demostrar funcionalidades, decisiones de diseño y lecciones '
                          'aprendidas',
                          'c) Solo leer el código línea por línea sin contexto',
                          'd) Entregar sin criterios de aceptación'],
             'pregunta': 'En la preparación de la presentación/evaluación del proyecto, un '
                         'elemento esencial es:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': 'V',
             'enunciado': 'try/catch permite manejar errores recuperables sin terminar '
                          'abruptamente toda la aplicación.',
             'id': 'B1',
             'justificacion': 'Manejo controlado de excepciones.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'Integrar módulos solo consiste en copiar/pegar clases en un único '
                          'archivo .java.',
             'id': 'B2',
             'justificacion': 'Implica contratos, dependencias, pruebas de integración y '
                              'estructura de paquetes.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'finally se ejecuta (salvo casos extremos de aborto de JVM) tanto si '
                          'hubo excepción como si no.',
             'id': 'B3',
             'justificacion': 'Bloque de limpieza típico.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'Una buena checklist de code review incluye legibilidad, nombres, manejo '
                          'de errores y cobertura de casos límite.',
             'id': 'B4',
             'justificacion': 'Práctica estándar de revisión cruzada.',
             'pts': 5,
             'tipo': 'vf'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Verdadero / Falso'},
 {'intro': '',
  'items': [{'enunciado': 'Su Proyecto Integrador tiene módulos: (1) dominio/modelo, (2) '
                          'persistencia en archivo, (3) GUI. Describa un plan de integración de 4 '
                          'pasos y 2 pruebas de integración que ejecutaría antes de la '
                          'sustentación.',
             'id': 'C1',
             'lineas': 7,
             'pts': 25,
             'solucion': ['Pasos posibles: contratos de interfaces → integrar modelo+persistencia '
                          '→ conectar GUI → prueba end-to-end.',
                          'Pruebas: guardar/cargar desde GUI; flujo completo CRUD; manejo de '
                          'archivo inexistente.',
                          'Rúbrica: 12 pts plan + 10 pts pruebas + 3 pts claridad.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Caso de integración'},
 {'intro': '',
  'items': [{'codigo': 'public List<Producto> cargar(Path p) {\n'
                       '  // proponga try/catch/finally o try-with-resources\n'
                       '}',
             'enunciado': 'Complete un manejo de excepciones adecuado para lectura de archivo. '
                          'Indique qué mensaje mostraría al usuario y qué registraría para '
                          'depuración.',
             'id': 'D1',
             'lineas': 6,
             'pts': 20,
             'solucion': ['try-with-resources; capturar IOException; mensaje amigable; log/print '
                          'stack en consola docente.',
                          'No tragar excepción vacía. 20 pts completo; 10 parcial.'],
             'tipo': 'practica'},
            {'enunciado': 'Redacte 5 ítems de una checklist de revisión de código cruzada '
                          'aplicables a un PR/módulo Java del curso.',
             'id': 'D2',
             'lineas': 5,
             'pts': 15,
             'solucion': ['Compila; nombres claros; sin código muerto; excepciones manejadas; '
                          'pruebas/manual smoke; encapsulamiento; sin secretos.',
                          '3 pts por ítem válido (máx 15).'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Práctica'}],
}

SEM_P1 = {
    "meta": _meta(
        curso_dir='Seminario de Sistemas',
        asignatura='Seminario de Sistemas',
        codigo='FI303301',
        grupo='341C',
        periodo='2026-2',
        horario='Jueves 20:00 – 22:00',
        n=1,
        corte=1,
        valor_corte='10% del Corte 1 (30%)',
        fecha='10/09/2026',
        clase=5,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 1 — Ciclos de vida y metodologías',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Emparejamiento — 20 pts',
 'C. Desarrollo — 25 pts',
 'D. Caso de estudio — 35 pts'],
        archivo='Parcial 1 - Ciclos de vida y metodologias',
        cobertura='Corte 1 · Únicamente clases con fecha <= 10/09/2026 (Clases 1-5):',
        temas=[
            _tema(1, '13/08', 'Conceptos iniciales'),
            _tema(2, '20/08', 'Ciclos de vida'),
            _tema(3, '27/08', 'Metodologías tradicionales'),
            _tema(4, '03/09', 'Metodologías ágiles'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Solo la fase de codificación',
                          'b) Las etapas desde la concepción hasta el retiro/mantenimiento',
                          'c) Únicamente las pruebas de caja negra',
                          'd) El diseño gráfico de interfaces'],
             'pregunta': 'El ciclo de vida del software describe:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Iteraciones cortas con entrega continua obligatoria',
                          'b) Fases secuenciales con poca vuelta atrás formal',
                          'c) Ausencia total de documentación',
                          'd) No definir requisitos'],
             'pregunta': 'El modelo en cascada se caracteriza por:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Rechazar todo contacto con el cliente',
                          'b) Entregas incrementales, feedback frecuente y adaptación al cambio',
                          'c) Prohibir las pruebas',
                          'd) Eliminar roles del equipo'],
             'pregunta': 'Una diferencia clave de las metodologías ágiles frente a las '
                         'tradicionales es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Cascadas anuales fijas',
                          'b) Sprints / iteraciones cortas',
                          'c) Un único hito final sin revisión',
                          'd) Solo diagramas ER'],
             'pregunta': 'Scrum, como marco ágil, organiza el trabajo típicamente en:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': '1-c, 2-b, 3-a, 4-d',
             'col_a': ['1) Cascada',
                       '2) Prototipado',
                       '3) Scrum',
                       '4) Extreme Programming (XP) — idea'],
             'col_b': ['a) Iteraciones con Product Backlog, Sprint y roles definidos',
                       'b) Construcción temprana de versiones para validar requisitos',
                       'c) Secuencia lineal de fases',
                       'd) Énfasis en prácticas técnicas (pruebas, integración frecuente, '
                       'simplicidad)'],
             'id': 'B1',
             'instruccion': 'Empareje metodología/modelo con su rasgo distintivo.',
             'pts': 20,
             'tipo': 'match'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Emparejamiento'},
 {'intro': '',
  'items': [{'enunciado': 'Defina ciclo de vida del software y nombre al menos 4 fases típicas, '
                          'explicando el propósito de cada una en una línea.',
             'id': 'C1',
             'lineas': 5,
             'pts': 12,
             'solucion': ['Definición + fases: requisitos, diseño, implementación, pruebas, '
                          'despliegue, mantenimiento.',
                          'Rúbrica: 4 definición + 8 fases (2 c/u).'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Compare en una tabla mental (texto) metodologías tradicionales vs '
                          'ágiles en: cambio de requisitos, documentación y frecuencia de entrega.',
             'id': 'C2',
             'lineas': 5,
             'pts': 13,
             'solucion': ['Tradicional: cambio costoso, docs extensas, entrega tardía.',
                          'Ágil: cambio esperado, docs suficientes, entregas frecuentes.',
                          'Rúbrica: 4 pts por dimensión (máx 12) + 1 claridad.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Desarrollo'},
 {'intro': '',
  'items': [{'contexto': 'Justifique con argumentos del Corte 1 (ciclos de vida y metodologías).',
             'enunciado': 'Caso: una clínica veterinaria necesita un sistema de citas. Los '
                          'requisitos aún son inciertos y el cliente quiere ver avances cada 2 '
                          'semanas.',
             'id': 'D1',
             'lineas': 9,
             'pts': 35,
             'requerimientos': ['a) ¿Qué enfoque metodológico recomendaría y por qué? (10 pts)',
                                'b) ¿Qué riesgos tendría usar cascada pura aquí? (10 pts)',
                                'c) Proponga un ciclo de 3 sprints con objetivo de cada uno (15 '
                                'pts)'],
             'solucion': ['Ágil/Scrum por incertidumbre y feedback (10).',
                          'Cascada: retrabajo tardío, poca validación temprana (10).',
                          'Sprints: backlog citas; CRUD/agenda; notificaciones/reporte (15).'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso de estudio'}],
}

SEM_P2 = {
    "meta": _meta(
        curso_dir='Seminario de Sistemas',
        asignatura='Seminario de Sistemas',
        codigo='FI303301',
        grupo='341C',
        periodo='2026-2',
        horario='Jueves 20:00 – 22:00',
        n=2,
        corte=2,
        valor_corte='10% del Corte 2 (30%)',
        fecha='15/10/2026',
        clase=10,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 2 — Requerimientos, UML y casos de uso',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Verdadero / Falso — 20 pts',
 'C. Historias y requerimientos — 25 pts',
 'D. Caso UML / casos de uso — 35 pts'],
        archivo='Parcial 2 - Requerimientos UML y casos de uso',
        cobertura=('Corte 2 · Únicamente clases con fecha <= 15/10/2026 en la ventana del corte '
 '(Clases 6-10). No evalúa ciclos de vida/metodologías del Corte 1:'),
        temas=[
            _tema(6, '17/09', 'Requerimientos de software'),
            _tema(7, '24/09', 'Historias de usuario'),
            _tema(8, '01/10', 'Introducción a UML'),
            _tema(9, '08/10', 'Casos de uso'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) El color corporativo únicamente',
                          'b) Una capacidad o comportamiento que el sistema debe ofrecer',
                          'c) Solo el presupuesto del proyecto',
                          'd) La marca del computador del desarrollador'],
             'pregunta': 'Un requerimiento funcional describe:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A2',
             'opciones': ['a) Como <rol>, quiero <objetivo>, para <beneficio>',
                          'b) SELECT * FROM historia',
                          'c) Solo un diagrama de clases',
                          'd) Un contrato legal notariado'],
             'pregunta': 'El formato típico de historia de usuario es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Un lenguaje de programación compilado',
                          'b) Un lenguaje de modelado para visualizar y documentar sistemas',
                          'c) Un motor de base de datos',
                          'd) Un protocolo de red'],
             'pregunta': 'UML es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Una clase abstracta interna obligatoria',
                          'b) Un rol externo que interactúa con el sistema',
                          'c) Un servidor físico',
                          'd) Un caso de prueba unitaria'],
             'pregunta': 'En un diagrama de casos de uso, un actor representa:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': 'V',
             'enunciado': 'Los requerimientos no funcionales incluyen aspectos como rendimiento, '
                          'seguridad y usabilidad.',
             'id': 'B1',
             'justificacion': 'Calidad del servicio / restricciones.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'Una historia de usuario no necesita criterios de aceptación.',
             'id': 'B2',
             'justificacion': 'Los criterios de aceptación definen «terminado».',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'include en casos de uso indica comportamiento común reutilizado por '
                          'otros casos.',
             'id': 'B3',
             'justificacion': 'Relación include de UML.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'UML solo sirve para dibujar pantallas (wireframes) y no modela '
                          'comportamiento.',
             'id': 'B4',
             'justificacion': 'UML cubre estructura y comportamiento (casos de uso, secuencia, '
                              'etc.).',
             'pts': 5,
             'tipo': 'vf'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Verdadero / Falso'},
 {'intro': '',
  'items': [{'enunciado': 'Escriba 2 requerimientos funcionales y 2 no funcionales para un sistema '
                          'de préstamo de equipos en la universidad.',
             'id': 'C1',
             'lineas': 5,
             'pts': 12,
             'solucion': ['RF: registrar préstamo; consultar disponibilidad.',
                          'RNF: respuesta < 2s; autenticación; disponibilidad 99%.',
                          '3 pts c/u bien clasificado (máx 12).'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Redacte 2 historias de usuario con criterios de aceptación (al menos 2 '
                          'criterios por historia).',
             'id': 'C2',
             'lineas': 5,
             'pts': 13,
             'solucion': ['Formato rol/quiero/para + criterios Given/When/Then o lista '
                          'verificable.',
                          'Rúbrica: 6 y 7 pts por historia completa.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Historias y requerimientos'},
 {'intro': '',
  'items': [{'enunciado': 'Para un sistema de inscripción a electivas:',
             'id': 'D1',
             'lineas': 9,
             'pts': 35,
             'requerimientos': ['a) Liste 3 actores y 5 casos de uso (10 pts)',
                                'b) Describa textual un caso de uso (nombre, actor, '
                                'precondiciones, flujo principal, postcondiciones) (15 pts)',
                                'c) Indique un include o extend justificado (10 pts)'],
             'solucion': ['Actores: Estudiante, Coordinador, Sistema pagos…',
                          'CU: Inscribir electiva, Consultar cupos, Cancelar, etc.',
                          'Descripción completa del flujo; include Autenticar.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso UML / casos de uso'}],
}

SEM_P3 = {
    "meta": _meta(
        curso_dir='Seminario de Sistemas',
        asignatura='Seminario de Sistemas',
        codigo='FI303301',
        grupo='341C',
        periodo='2026-2',
        horario='Jueves 20:00 – 22:00',
        n=3,
        corte=3,
        valor_corte='15% del Corte 3 (40%)',
        fecha='19/11/2026',
        clase=15,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 3 — UML avanzado, interfaces y proyecto',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Emparejamiento — 20 pts',
 'C. Diseño UML / UI — 25 pts',
 'D. Caso de sustentación de proyecto — 35 pts'],
        archivo='Parcial 3 - UML avanzado interfaces y proyecto',
        cobertura=('Corte 3 · Únicamente clases con fecha <= 19/11/2026 en la ventana del corte '
 '(Clases 11-15):'),
        temas=[
            _tema(11, '22/10', 'Avance proyecto integrador'),
            _tema(12, '29/10', 'Diagramas UML avanzados'),
            _tema(13, '05/11', 'Diseño de interfaces'),
            _tema(14, '12/11', 'Evaluación final (prep. sustentación) · Sustentación de proyectos + cierre'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Solo la herencia entre clases',
                          'b) El intercambio de mensajes entre objetos a lo largo del tiempo',
                          'c) El modelo entidad-relación',
                          'd) La topología de red física'],
             'pregunta': 'Un diagrama de secuencia UML enfatiza:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Cero instancias exactamente',
                          'b) Una o muchas instancias',
                          'c) Herencia múltiple obligatoria',
                          'd) Un paquete cerrado'],
             'pregunta': 'En un diagrama de clases, la multiplicidad 1..* en una asociación '
                         'indica:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Saturar la pantalla con todas las funciones a la vez',
                          'b) Claridad, consistencia, feedback al usuario y flujos simples',
                          'c) Ocultar mensajes de error siempre',
                          'd) Evitar etiquetas en los campos'],
             'pregunta': 'Una buena práctica de diseño de interfaces (UI) es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Improvisar sin trazabilidad a requisitos',
                          'b) Demostrar avance, artefactos (UML/UI) y decisiones frente a los '
                          'objetivos',
                          'c) Entregar solo código sin explicación',
                          'd) Omitir limitaciones conocidas'],
             'pregunta': 'En la sustentación del proyecto integrador se espera principalmente:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': '1-a, 2-b, 3-c, 4-d',
             'col_a': ['1) Diagrama de clases',
                       '2) Diagrama de secuencia',
                       '3) Wireframe / mockup UI',
                       '4) Diagrama de estados (idea)'],
             'col_b': ['a) Muestra estructura estática (atributos, operaciones, relaciones)',
                       'b) Muestra interacción temporal entre objetos',
                       'c) Bosqueja pantallas y disposición de controles',
                       'd) Muestra ciclos de vida/estados de un objeto'],
             'id': 'B1',
             'instruccion': 'Relacione el artefacto con su propósito.',
             'pts': 20,
             'tipo': 'match'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Emparejamiento'},
 {'intro': '',
  'items': [{'enunciado': 'Proponga 3 clases del dominio de su proyecto (nombre + 2 atributos + 1 '
                          'relación entre ellas).',
             'id': 'C1',
             'lineas': 5,
             'pts': 12,
             'solucion': ['Clases coherentes al dominio + relación (asociación/composición) '
                          'justificada.',
                          '4 pts por clase/relación bien planteada (máx 12).'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Liste 4 principios o heurísticas de UI aplicables a la pantalla '
                          'principal de su sistema y explique cada una en una línea.',
             'id': 'C2',
             'lineas': 5,
             'pts': 13,
             'solucion': ['Visibilidad de estado; correspondencia con mundo real; consistencia; '
                          'prevención de errores; feedback.',
                          'Rúbrica: ~3 pts c/u.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Diseño UML / UI'},
 {'intro': '',
  'items': [{'enunciado': 'Elabore un guion breve de sustentación (máx. estructura pedida) para el '
                          'Proyecto Integrador del Seminario:',
             'id': 'D1',
             'lineas': 10,
             'pts': 35,
             'requerimientos': ['a) Problema y objetivo (5 pts)',
                                'b) Alcance / fuera de alcance (5 pts)',
                                'c) 2 artefactos UML que mostraría y qué demuestran (10 pts)',
                                'd) 1 flujo UI crítico paso a paso (10 pts)',
                                'e) Riesgos o trabajo futuro (5 pts)'],
             'solucion': ['Coherencia problema-objetivo-alcance; UML con propósito; UI navegable; '
                          'riesgos realistas.',
                          'Asignar pts según rúbrica del enunciado.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso de sustentación'}],
}

BD2_P1 = {
    "meta": _meta(
        curso_dir='Bases de Datos II',
        asignatura='Bases de Datos II',
        codigo='FI303215',
        grupo='641A-2',
        periodo='2026-2',
        horario='Lunes 18:00 – 20:00',
        n=1,
        corte=1,
        valor_corte='10% del Corte 1 (30%)',
        fecha='07/09/2026',
        clase=5,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 1 — Administración, procedimientos y seguridad',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Verdadero / Falso — 20 pts',
 'C. SQL / objetos programables — 25 pts',
 'D. Caso seguridad y respaldo — 35 pts'],
        archivo='Parcial 1 - Administracion procedimientos y seguridad',
        cobertura='Corte 1 · Únicamente clases con fecha <= 07/09/2026 (Clases 1-5):',
        temas=[
            _tema(1, '10/08', 'Revisión de Bases de Datos I'),
            _tema(2, '17/08', 'Administración de bases de datos (autónoma)'),
            _tema(3, '24/08', 'Procedimientos almacenados'),
            _tema(4, '31/08', 'Funciones y disparadores · Seguridad y respaldo'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Un índice clusterizado',
                          'b) Un programa SQL persistido en el SGBD que puede recibir parámetros y '
                          'ejecutar lógica',
                          'c) Un archivo CSV externo',
                          'd) Una vista materializada obligatoria'],
             'pregunta': 'Un procedimiento almacenado es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Solo al iniciar el sistema operativo',
                          'b) Ante eventos DML/DDL definidos (INSERT/UPDATE/DELETE, según SGBD)',
                          'c) Únicamente con SELECT',
                          'd) Nunca de forma automática'],
             'pregunta': 'Un trigger (disparador) se ejecuta:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) No poder existir en el catálogo',
                          'b) Retornar un valor y usarse en expresiones SQL',
                          'c) Reemplazar al motor de transacciones',
                          'd) Eliminar la necesidad de permisos'],
             'pregunta': 'Una función almacenada, a diferencia típica de un procedimiento, suele:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Usar un único usuario root/sa para todas las apps',
                          'b) Principio de mínimo privilegio y roles/permisos acotados',
                          'c) Compartir contraseñas en el chat del curso',
                          'd) Desactivar respaldos para ganar espacio'],
             'pregunta': 'Una práctica de seguridad en BD es:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': 'V',
             'enunciado': 'Un respaldo (backup) completo permite recuperar la BD ante pérdida o '
                          'corrupción, según la política definida.',
             'id': 'B1',
             'justificacion': 'Objetivo del backup/restore.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'GRANT y REVOKE no tienen relación con el control de acceso en SQL.',
             'id': 'B2',
             'justificacion': 'Son el mecanismo estándar de privilegios.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'Los disparadores pueden usarse para auditar cambios (registrar quién '
                          'modificó qué).',
             'id': 'B3',
             'justificacion': 'Caso típico de auditoría.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'La administración de BD incluye usuarios, espacios, mantenimiento y '
                          'monitoreo, no solo escribir SELECT.',
             'id': 'B4',
             'justificacion': 'Alcance DBA alineado al plan.',
             'pts': 5,
             'tipo': 'vf'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Verdadero / Falso'},
 {'intro': '',
  'items': [{'enunciado': 'Escriba un procedimiento almacenado (sintaxis MySQL/PostgreSQL o SQL '
                          'claro) sp_registrar_prestamo que reciba id_usuario, id_equipo y valide '
                          'que el equipo esté disponible antes de insertar.',
             'id': 'C1',
             'lineas': 6,
             'pts': 15,
             'solucion': ['Parámetros IN; SELECT estado; IF disponible THEN INSERT; ELSE '
                          'señal/error.',
                          'Rúbrica: firma 4 + validación 6 + insert/error 5.'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Proponga un trigger AFTER UPDATE sobre una tabla Prestamo que inserte '
                          'un registro en Auditoria_Prestamo con fecha y valores relevantes.',
             'id': 'C2',
             'lineas': 4,
             'pts': 10,
             'solucion': ['AFTER UPDATE ON Prestamo FOR EACH ROW INSERT INTO Auditoria… NEW/OLD.',
                          'Rúbrica: evento correcto 4 + cuerpo 6.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — SQL / objetos programables'},
 {'intro': '',
  'items': [{'enunciado': 'Una pyme pierde datos por borrado accidental. Diseñe una política '
                          'mínima de seguridad y respaldo:',
             'id': 'D1',
             'lineas': 9,
             'pts': 35,
             'requerimientos': ['a) 3 controles de acceso (roles/privilegios) (9 pts)',
                                'b) Tipo de backup (completo/incremental/idea) y frecuencia '
                                'justificada (10 pts)',
                                'c) Prueba de restauración: qué validaría (8 pts)',
                                'd) Relacione cómo un procedimiento podría restringir operaciones '
                                'sensibles (8 pts)'],
             'solucion': ['Roles app_readonly/app_write/dba; backups diarios + semanal completo; '
                          'restore drill; SP con validaciones.',
                          'Asignar según rúbrica del enunciado.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso seguridad y respaldo'}],
}

BD2_P2 = {
    "meta": _meta(
        curso_dir='Bases de Datos II',
        asignatura='Bases de Datos II',
        codigo='FI303215',
        grupo='641A-2',
        periodo='2026-2',
        horario='Lunes 18:00 – 20:00',
        n=2,
        corte=2,
        valor_corte='10% del Corte 2 (30%)',
        fecha='05/10/2026',
        clase=9,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 2 — Optimización, índices y transacciones',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Emparejamiento — 20 pts',
 'C. Optimización SQL — 25 pts',
 'D. Caso transacciones / tuning — 35 pts'],
        archivo='Parcial 2 - Optimizacion indices y transacciones',
        cobertura=('Corte 2 · Únicamente clases con fecha <= 05/10/2026 (Clases 6-9). NO incluye '
 'Clase 10 (concurrencia, 12/10):'),
        temas=[
            _tema(6, '14/09', 'Optimización de consultas'),
            _tema(7, '21/09', 'Índices y particionamiento'),
            _tema(8, '28/09', 'Tuning de bases de datos · Gestión de transacciones'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Eliminar la necesidad de WHERE',
                          'b) Acelerar búsquedas/filtros/ordenamientos sobre columnas indexadas',
                          'c) Reemplazar las transacciones',
                          'd) Garantizar normalización 5FN'],
             'pregunta': 'Un índice B-Tree típico ayuda principalmente a:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Borrar tablas rápidamente',
                          'b) Analizar cómo el optimizador accederá a los datos',
                          'c) Crear usuarios',
                          'd) Compactar el sistema operativo'],
             'pregunta': 'EXPLAIN / plan de ejecución se usa para:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Que las transacciones son visibles a medias',
                          'b) Todo o nada: o se confirman todos los cambios o ninguno',
                          'c) Que no hay aislamiento',
                          'd) Que el disco no puede fallar'],
             'pregunta': 'ACID: la «A» (Atomicity) significa:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A4',
             'opciones': ['a) Dividir grandes volúmenes para administración y rendimiento',
                          'b) Eliminar claves primarias',
                          'c) Prohibir índices',
                          'd) Convertir SQL en NoSQL automáticamente'],
             'pregunta': 'El particionamiento de tablas busca, entre otros:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': '1-a, 2-b, 3-c, 4-d',
             'col_a': ['1) COMMIT', '2) ROLLBACK', '3) Índice compuesto', '4) Full table scan'],
             'col_b': ['a) Confirma definitivamente los cambios de la transacción',
                       'b) Deshace cambios no confirmados',
                       'c) Índice sobre varias columnas',
                       'd) Lectura completa de la tabla; a menudo costosa en tablas grandes'],
             'id': 'B1',
             'instruccion': 'Empareje concepto de transacciones/tuning.',
             'pts': 20,
             'tipo': 'match'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Emparejamiento'},
 {'intro': '',
  'items': [{'enunciado': "Dada la consulta: SELECT * FROM Pedido WHERE fecha >= '2026-01-01' AND "
                          'cliente_id = 45; proponga 3 mejoras de optimización (índices, '
                          'proyección de columnas, etc.) y justifique.',
             'id': 'C1',
             'lineas': 5,
             'pts': 15,
             'solucion': ['Evitar SELECT *; índice (cliente_id, fecha); estadísticas actualizadas; '
                          'evitar funciones sobre columna filtrada.',
                          '5 pts por mejora válida justificada (máx 15).'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Explique una ventaja y un costo/riesgo de crear muchos índices en una '
                          'tabla de alta escritura.',
             'id': 'C2',
             'lineas': 3,
             'pts': 10,
             'solucion': ['Ventaja: lecturas más rápidas. Costo: más espacio y escrituras más '
                          'lentas (mantenimiento de índices).'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Optimización SQL'},
 {'intro': '',
  'items': [{'enunciado': 'Transferencia entre cuentas: debitar A y acreditar B debe ser atómica.',
             'id': 'D1',
             'lineas': 9,
             'pts': 35,
             'requerimientos': ['a) Escriba pseudocódigo/SQL transaccional (BEGIN/COMMIT/ROLLBACK) '
                                '(15 pts)',
                                'b) Indique qué pasa si falla el crédito tras el débito sin '
                                'transacción (10 pts)',
                                'c) Mencione 2 acciones de tuning si el sistema reporta lentitud '
                                'en reportes mensuales (10 pts)'],
             'solucion': ['BEGIN; UPDATE A; UPDATE B; COMMIT; ROLLBACK on error.',
                          'Inconsistencia de saldos sin atomicidad.',
                          'Índices en fecha; agregados/particiones; materializar resumen.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso transacciones / tuning'}],
}

BD2_P3 = {
    "meta": _meta(
        curso_dir='Bases de Datos II',
        asignatura='Bases de Datos II',
        codigo='FI303215',
        grupo='641A-2',
        periodo='2026-2',
        horario='Lunes 18:00 – 20:00',
        n=3,
        corte=3,
        valor_corte='15% del Corte 3 (40%)',
        fecha='09/11/2026',
        clase=14,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 3 — Integración, casos y cierre de proyecto',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Verdadero / Falso — 20 pts',
 'C. Integración de aplicaciones — 25 pts',
 'D. Caso / preparación de sustentación BD — 35 pts'],
        archivo='Parcial 3 - Integracion casos y cierre de proyecto',
        cobertura=('Corte 3 · Únicamente clases con fecha <= 09/11/2026 (Clases 11-14). NO '
 'incluye Clase 15 (16/11):'),
        temas=[
            _tema(11, '19/10', 'Avance del proyecto final'),
            _tema(12, '26/10', 'Integración de aplicaciones externas · Preparación de presentación final'),
            _tema(13, '02/11', 'Análisis de casos reales (autónoma)'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Ignorar autenticación',
                          'b) Contratos de acceso (API/SQL), credenciales seguras y manejo de '
                          'errores',
                          'c) Desactivar todas las FK',
                          'd) Usar solo archivos Excel locales sin control'],
             'pregunta': 'Integrar una aplicación externa con la BD típicamente requiere:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Usar cuentas con privilegios mínimos',
                          'b) Embebir contraseñas en el código fuente público',
                          'c) Parametrizar consultas',
                          'd) Monitorear fallos de conexión'],
             'pregunta': 'Un anti-patrón al integrar apps con BD es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Copiar sin comprender',
                          'b) Extraer lecciones de arquitectura, rendimiento, seguridad o fallos',
                          'c) Evitar documentar',
                          'd) Eliminar el modelo relacional siempre'],
             'pregunta': 'En el análisis de casos reales de BD se busca:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Solo capturas sin explicar el avance',
                          'b) Avance del PI, integración con apps, lecciones de casos y guion de '
                          'sustentación',
                          'c) Únicamente el logo del SGBD',
                          'd) Código ofuscado sin demo'],
             'pregunta': 'Para la preparación de la presentación final del proyecto de BD II es '
                         'clave mostrar:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': 'V',
             'enunciado': 'Una API que consume la BD debe validar entradas para reducir inyección '
                          'SQL y datos inválidos.',
             'id': 'B1',
             'justificacion': 'Seguridad en integración.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'La integración externa nunca necesita considerar transacciones o '
                          'consistencia.',
             'id': 'B2',
             'justificacion': 'La consistencia sigue siendo crítica en integraciones.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'Documentar supuestos y limitaciones fortalece la sustentación del '
                          'proyecto.',
             'id': 'B3',
             'justificacion': 'Transparencia académica/profesional.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'Un avance de proyecto final debería alinear entregables con la '
                          'integración, análisis de casos y la preparación de la sustentación del '
                          'corte.',
             'id': 'B4',
             'justificacion': 'Trazabilidad con Clases 11–14 del Corte 3.',
             'pts': 5,
             'tipo': 'vf'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Verdadero / Falso'},
 {'intro': '',
  'items': [{'enunciado': 'Diseñe la integración de una app web/móvil con su BD del proyecto: '
                          'componentes, flujo de autenticación a BD (o vía API), y 3 fallos a '
                          'manejar (timeout, dato duplicado, permiso denegado).',
             'id': 'C1',
             'lineas': 7,
             'pts': 25,
             'solucion': ['App → API → BD; pool conexiones; errores mapeados a mensajes.',
                          'Rúbrica: arquitectura 10 + auth/acceso 7 + fallos 8.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Integración'},
 {'intro': '',
  'items': [{'enunciado': 'Prepare un esquema de presentación final (guion) de su proyecto de BD '
                          'II:',
             'id': 'D1',
             'lineas': 10,
             'pts': 35,
             'requerimientos': ['a) Problema y objetivos del PI (5 pts)',
                                'b) Estado de avance y entregables listos / pendientes (10 pts)',
                                'c) Diseño de integración con aplicación externa (API/SQL, '
                                'credenciales, errores) (10 pts)',
                                'd) Una lección de un caso real aplicable a su proyecto (5 pts)',
                                'e) Guion de presentación (orden de láminas / demo) (5 pts)'],
             'solucion': ['Evaluar completitud y coherencia con temas del Corte 3 (avance, '
                          'integración, casos, prep.); pts según rúbrica.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso / sustentación'}],
}

ARQ_P1 = {
    "meta": _meta(
        curso_dir='Arquitectura de Sistemas Computacionales',
        asignatura='Arquitectura de Sistemas Computacionales',
        codigo='FI303380',
        grupo='6303C',
        periodo='2026-2',
        horario='Lunes 10:00 – 12:00',
        n=1,
        corte=1,
        valor_corte='10% del Corte 1 (30%)',
        fecha='07/09/2026',
        clase=5,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 1 — Cloud, virtualización y distribuidos',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Emparejamiento — 20 pts',
 'C. Desarrollo arquitectónico — 25 pts',
 'D. Caso de diseño — 35 pts'],
        archivo='Parcial 1 - Cloud virtualizacion y distribuidos',
        cobertura='Corte 1 · Únicamente clases con fecha <= 07/09/2026 (Clases 1-5):',
        temas=[
            _tema(1, '10/08', 'Introducción a arquitecturas cloud'),
            _tema(2, '17/08', 'Modelos de servicio IaaS, PaaS, SaaS (autónoma)'),
            _tema(3, '24/08', 'Virtualización y contenedores'),
            _tema(4, '31/08', 'Microservicios · Arquitecturas distribuidas'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Solo una aplicación de correo lista para el usuario final',
                          'b) Infraestructura (cómputo, almacenamiento, red) como servicio',
                          'c) Únicamente IDEs en el navegador sin VMs',
                          'd) Un lenguaje de programación nuevo'],
             'pregunta': 'IaaS se caracteriza por ofrecer principalmente:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Son exactamente lo mismo en todos los niveles',
                          'b) Los contenedores comparten el kernel del host y suelen ser más '
                          'livianos',
                          'c) Las VM nunca aíslan recursos',
                          'd) Los contenedores requieren un hipervisor Type-1 siempre'],
             'pregunta': 'Respecto a máquinas virtuales y contenedores:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A3',
             'opciones': ['a) Imposible de desplegar',
                          'b) Despliegue e independencia de escalado por servicio (con mayor '
                          'complejidad operativa)',
                          'c) Eliminación total de redes',
                          'd) Un solo lenguaje obligatorio en todo el sistema'],
             'pregunta': 'Una ventaja de microservicios frente a un monolito es:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A4',
             'opciones': ['a) Que no exista latencia nunca',
                          'b) Consistencia, particiones de red y coordinación entre nodos',
                          'c) Que solo haya un proceso en un solo núcleo',
                          'd) La imposibilidad de usar APIs'],
             'pregunta': 'En arquitecturas distribuidas, un desafío típico es:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': '1-a, 2-b, 3-c, 4-d',
             'col_a': ['1) SaaS', '2) PaaS', '3) Contenedor', '4) Hipervisor'],
             'col_b': ['a) Aplicación consumida por el usuario final (p. ej. correo/oficina en '
                       'nube)',
                       'b) Plataforma para desplegar apps sin gestionar todo el SO',
                       'c) Empaqueta app + dependencias; comparte kernel del host',
                       'd) Software que permite ejecutar máquinas virtuales'],
             'id': 'B1',
             'instruccion': 'Empareje modelo/concepto con ejemplo o rasgo.',
             'pts': 20,
             'tipo': 'match'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Emparejamiento'},
 {'intro': '',
  'items': [{'enunciado': 'Compare IaaS, PaaS y SaaS indicando qué gestiona el proveedor vs el '
                          'cliente en cada uno (visión de responsabilidad).',
             'id': 'C1',
             'lineas': 5,
             'pts': 12,
             'solucion': ['IaaS: cliente gestiona SO/runtime/app; PaaS: cliente app/datos; SaaS: '
                          'cliente solo uso/configuración.',
                          'Rúbrica: 4 pts por modelo bien contrastado.'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Explique 2 beneficios y 2 retos de adoptar microservicios en un sistema '
                          'académico pequeño.',
             'id': 'C2',
             'lineas': 4,
             'pts': 13,
             'solucion': ['Beneficios: escalado selectivo, despliegues independientes.',
                          'Retos: observabilidad, latencia de red, consistencia, DevOps.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Desarrollo'},
 {'intro': '',
  'items': [{'enunciado': 'Diseñe una arquitectura cloud inicial para un sistema de gestión de '
                          'laboratorios con módulos: autenticación, reservas y notificaciones.',
             'id': 'D1',
             'lineas': 9,
             'pts': 35,
             'requerimientos': ['a) Elija IaaS/PaaS/SaaS (o híbrido) por componente y justifique '
                                '(10 pts)',
                                'b) Indique si usaría VM, contenedores o ambos (10 pts)',
                                'c) Proponga 3 servicios/microservicios y 2 riesgos distribuidos '
                                '(15 pts)'],
             'solucion': ['Auth/reservas en contenedores PaaS; email SaaS; riesgos: latencia, '
                          'fallos parciales, secretos.',
                          'Pts según rúbrica del enunciado.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso de diseño'}],
}

ARQ_P2 = {
    "meta": _meta(
        curso_dir='Arquitectura de Sistemas Computacionales',
        asignatura='Arquitectura de Sistemas Computacionales',
        codigo='FI303380',
        grupo='6303C',
        periodo='2026-2',
        horario='Lunes 10:00 – 12:00',
        n=2,
        corte=2,
        valor_corte='10% del Corte 2 (30%)',
        fecha='05/10/2026',
        clase=9,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 2 — Seguridad, redes, monitoreo y CI/CD',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Verdadero / Falso — 20 pts',
 'C. Seguridad y operaciones — 25 pts',
 'D. Caso CI/CD + monitoreo — 35 pts'],
        archivo='Parcial 2 - Seguridad redes monitoreo y CI-CD',
        cobertura=('Corte 2 · Únicamente clases con fecha <= 05/10/2026 (Clases 6-9). NO incluye '
 'Clase 10 (costos, 12/10):'),
        temas=[
            _tema(6, '14/09', 'Seguridad en la nube'),
            _tema(7, '21/09', 'Redes y almacenamiento cloud'),
            _tema(8, '28/09', 'Monitoreo y optimización · Integración continua y despliegue (CI/CD)'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'b',
             'id': 'A1',
             'opciones': ['a) Que el proveedor hace todo y el cliente nada',
                          'b) Que proveedor y cliente dividen responsabilidades de seguridad según '
                          'el servicio',
                          'c) Que no hay cifrado posible',
                          'd) Que las redes públicas no existen'],
             'pregunta': 'El modelo de responsabilidad compartida en cloud implica:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Solo registros DNS',
                          'b) Almacenar objetos/archivos escalables (backups, media, logs)',
                          'c) Reemplazar CPU',
                          'd) Ejecutar el navegador web'],
             'pregunta': 'Object storage (p. ej. buckets) se usa típicamente para:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A3',
             'opciones': ['a) Integrar cambios con frecuencia y validarlos con builds/pruebas '
                          'automáticas',
                          'b) Evitar cualquier repositorio',
                          'c) Desplegar a producción sin pruebas siempre',
                          'd) Eliminar el monitoreo'],
             'pregunta': 'CI (Integración Continua) busca principalmente:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A4',
             'opciones': ['a) Latencia, tasa de error y uso de CPU/memoria',
                          'b) Solo el color del logo',
                          'c) El número de diapositivas del proyecto',
                          'd) La versión de Word del docente'],
             'pregunta': 'Una métrica útil de monitoreo de un servicio cloud es:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': 'V',
             'enunciado': 'Exponer puertos innecesarios en un grupo de seguridad/firewall aumenta '
                          'la superficie de ataque.',
             'id': 'B1',
             'justificacion': 'Principio de mínimo acceso de red.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'CD (Continuous Delivery/Deployment) automatiza la ruta hacia entornos '
                          '(con controles) tras CI.',
             'id': 'B2',
             'justificacion': 'Pipeline de entrega.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'F',
             'enunciado': 'El monitoreo solo sirve después de un incidente grave, no de forma '
                          'continua.',
             'id': 'B3',
             'justificacion': 'Monitoreo proactivo y alertas.',
             'pts': 5,
             'tipo': 'vf'},
            {'clave': 'V',
             'enunciado': 'VPC/redes virtuales permiten aislar recursos y controlar tráfico entre '
                          'subredes.',
             'id': 'B4',
             'justificacion': 'Aislamiento de red cloud.',
             'pts': 5,
             'tipo': 'vf'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Verdadero / Falso'},
 {'intro': '',
  'items': [{'enunciado': 'Liste 4 controles de seguridad cloud aplicables a un API desplegada en '
                          'la nube (identidad, red, secretos, logs).',
             'id': 'C1',
             'lineas': 4,
             'pts': 12,
             'solucion': ['IAM/roles; TLS; secret manager; WAF/SG; logging/auditoría.',
                          '3 pts por control válido (máx 12).'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Explique la diferencia entre almacenamiento de bloques, archivos y '
                          'objetos con un ejemplo de uso cloud para cada uno.',
             'id': 'C2',
             'lineas': 5,
             'pts': 13,
             'solucion': ['Block: discos de VM; File: NFS compartido; Object: backups/media en '
                          'bucket.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Seguridad y operaciones'},
 {'intro': '',
  'items': [{'enunciado': 'Diseñe un pipeline CI/CD sencillo (etapas) para un servicio '
                          'containerizado y defina 3 alertas de monitoreo post-despliegue.',
             'id': 'D1',
             'lineas': 9,
             'pts': 35,
             'requerimientos': ['a) Etapas del pipeline (build, test, scan, deploy…) (15 pts)',
                                'b) Entornos (dev/staging/prod) y criterio de promoción (10 pts)',
                                'c) 3 alertas con umbral o condición (10 pts)'],
             'solucion': ['CI: lint/test/build image; CD: staging→prod con aprobación; alertas: '
                          '5xx, latencia p95, CPU.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso CI/CD + monitoreo'}],
}

ARQ_P3 = {
    "meta": _meta(
        curso_dir='Arquitectura de Sistemas Computacionales',
        asignatura='Arquitectura de Sistemas Computacionales',
        codigo='FI303380',
        grupo='6303C',
        periodo='2026-2',
        horario='Lunes 10:00 – 12:00',
        n=3,
        corte=3,
        valor_corte='15% del Corte 3 (40%)',
        fecha='09/11/2026',
        clase=14,
        tiempo='90–100 minutos',
        titulo_parcial='Parcial 3 — Rendimiento, escalabilidad y cierre de proyecto',
        secciones_resumen=['A. Selección múltiple — 20 pts',
 'B. Emparejamiento — 20 pts',
 'C. Rendimiento y escalabilidad — 25 pts',
 'D. Caso de sustentación arquitectónica — 35 pts'],
        archivo='Parcial 3 - Rendimiento escalabilidad y cierre de proyecto',
        cobertura=('Corte 3 · Únicamente clases con fecha <= 09/11/2026 (Clases 11-14). NO '
 'incluye Clase 15 (16/11):'),
        temas=[
            _tema(11, '19/10', 'Avance del proyecto final'),
            _tema(12, '26/10', 'Pruebas de rendimiento · Preparación de presentación final'),
            _tema(13, '02/11', 'Escalabilidad automática (autónoma)'),
        ],
    ),
    "secciones": [{'intro': '',
  'items': [{'clave': 'a',
             'id': 'A1',
             'opciones': ['a) Evaluar el comportamiento bajo una carga esperada/concurrencia '
                          'definida',
                          'b) Solo revisar ortografía del README',
                          'c) Eliminar logs',
                          'd) Cambiar el color de la UI'],
             'pregunta': 'Una prueba de carga (load test) busca:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'b',
             'id': 'A2',
             'opciones': ['a) Aumentar CPU de una sola máquina únicamente',
                          'b) Añadir más instancias/nodos para repartir carga',
                          'c) Reducir usuarios a la fuerza',
                          'd) Apagar el balanceador siempre'],
             'pregunta': 'Escalabilidad horizontal significa típicamente:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A3',
             'opciones': ['a) Métricas (CPU, RPS, latencia) según políticas',
                          'b) La fase lunar',
                          'c) El número de diapositivas',
                          'd) Un único valor fijo imposible de cambiar'],
             'pregunta': 'El autoescalado (autoscaling) reacciona generalmente a:',
             'pts': 5,
             'tipo': 'mcq'},
            {'clave': 'a',
             'id': 'A4',
             'opciones': ['a) Diagrama de arquitectura, decisiones, evidencia de pruebas y '
                          'trade-offs',
                          'b) Solo el código ofuscado',
                          'c) Ningún diagrama',
                          'd) Credenciales de producción en la lámina'],
             'pregunta': 'En la preparación de la presentación final arquitectónica conviene '
                         'incluir:',
             'pts': 5,
             'tipo': 'mcq'}],
  'pts': 20,
  'titulo': 'SECCIÓN A — Selección múltiple'},
 {'intro': '',
  'items': [{'clave': '1-a, 2-b, 3-c, 4-d',
             'col_a': ['1) Stress test',
                       '2) Spike test',
                       '3) Escalabilidad vertical',
                       '4) Balanceador de carga'],
             'col_b': ['a) Empuja el sistema más allá de la capacidad normal para hallar límites',
                       'b) Evalúa picos súbitos de tráfico',
                       'c) Aumentar recursos de un mismo nodo (más CPU/RAM)',
                       'd) Distribuye peticiones entre instancias'],
             'id': 'B1',
             'instruccion': 'Empareje tipo de prueba/escalado con su definición.',
             'pts': 20,
             'tipo': 'match'}],
  'pts': 20,
  'titulo': 'SECCIÓN B — Emparejamiento'},
 {'intro': '',
  'items': [{'enunciado': 'Defina 3 métricas de rendimiento que mediría en su API y un umbral de '
                          'aceptación ejemplo para cada una.',
             'id': 'C1',
             'lineas': 4,
             'pts': 12,
             'solucion': ['p95 latencia, error rate, throughput; umbrales realistas justificados.'],
             'tipo': 'desarrollo'},
            {'enunciado': 'Explique cuándo preferiría escalado vertical vs horizontal y un límite '
                          'de cada enfoque.',
             'id': 'C2',
             'lineas': 4,
             'pts': 13,
             'solucion': ['Vertical: simple hasta techo de máquina; horizontal: más nodos, '
                          'necesita stateless/balanceo.'],
             'tipo': 'desarrollo'}],
  'pts': 25,
  'titulo': 'SECCIÓN C — Rendimiento y escalabilidad'},
 {'intro': '',
  'items': [{'enunciado': 'Elabore el guion de sustentación de su proyecto de Arquitectura '
                          '(enfoque cloud):',
             'id': 'D1',
             'lineas': 10,
             'pts': 35,
             'requerimientos': ['a) Contexto y objetivos (5 pts)',
                                'b) Diagrama lógico (describa capas/servicios) (10 pts)',
                                'c) Estrategia de pruebas de rendimiento (10 pts)',
                                'd) Política de escalado automático propuesta (5 pts)',
                                'e) Riesgos, limitaciones o trabajo futuro del avance (5 pts)'],
             'solucion': ['Coherencia arquitectura-pruebas-escalado; trade-offs claros; sin '
                          'secretos en láminas.'],
             'tipo': 'practica'}],
  'pts': 35,
  'titulo': 'SECCIÓN D — Caso de sustentación'}],
}

TODOS = [
    PROG2_P1,
    PROG2_P2,
    PROG2_P3,
    SEM_P1,
    SEM_P2,
    SEM_P3,
    BD2_P1,
    BD2_P2,
    BD2_P3,
    ARQ_P1,
    ARQ_P2,
    ARQ_P3,
]
